# Pandas GroupBy - Big Programe 2

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("imdb-top-1000.csv.xls")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [3]:
df["Released_Year"]=pd.to_numeric(df["Released_Year"],errors="coerce")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [4]:
df["IMDB_Rating"]=pd.to_numeric(df["IMDB_Rating"],errors="coerce")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [5]:
df["No_of_Votes	"]=pd.to_numeric(df["No_of_Votes"],errors="coerce")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,2343110
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1620367
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,1129952
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,689845
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,166544
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,34075
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,43374
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,26471
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,51853

In [6]:
df["Gross"]=pd.to_numeric(df["Gross"],errors="coerce")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,2343110
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1620367
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,1129952
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,689845
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,166544
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,34075
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,43374
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,26471
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,51853

In [7]:
df["Metascore"]=pd.to_numeric(df["Metascore"],errors="coerce")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,2343110
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1620367
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,1129952
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,689845
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,166544
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,34075
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,43374
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,26471
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,51853

In [8]:
director_rating=df.groupby("Director")["IMDB_Rating"].mean().sort_values(ascending=False)
director_rating

Director
Frank Darabont        8.95
Lana Wachowski        8.70
Irvin Kershner        8.70
Masaki Kobayashi      8.60
Fernando Meirelles    8.60
                      ...
Tom Tykwer            7.60
Bennett Miller        7.60
Blake Edwards         7.60
Aneesh Chaganty       7.60
Walter Hill           7.60
Name: IMDB_Rating, Length: 548, dtype: float64

In [9]:
director_analysis=df.groupby("Director",as_index=False).agg(
     Movies=("Series_Title","count"),
    Average_Rating=("IMDB_Rating","max"),
    Highest_Rating=("IMDB_Rating","mean"),
    Average_Runtime=("Runtime","mean"),
    Total_Votes=("No_of_Votes","sum"),
    Total_Gross=("Gross","sum")
    )
director_analysis

,Director,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
0,Aamir Khan,1,8.4,8.40,165.0,168895,1223869.0
1,Aaron Sorkin,1,7.8,7.80,129.0,89896,853090410.0
2,Abdellatif Kechiche,1,7.7,7.70,180.0,138741,2199675.0
3,Abhishek Chaubey,1,7.8,7.80,148.0,27175,218428303.0
4,Abhishek Kapoor,1,7.7,7.70,130.0,32628,1122527.0
...,...,...,...,...,...,...,...
543,Zack Snyder,2,7.6,7.60,139.5,1233675,318124738.0
544,Zaza Urushadze,1,8.2,8.20,87.0,40382,144501.0
545,Zoya Akhtar,2,8.1,8.05,154.5,99813,8675019.0
546,Çagan Irmak,1,8.3,8.30,112.0,78925,461855363.0
547,Ömer Faruk Sorak,1,8.0,8.00,127.0,56960,196206077.0

In [10]:
director_analysis=director_analysis.sort_values(
    ["Movies","Average_Rating"],
    ascending=[False,False]
)
director_analysis

,Director,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
22,Alfred Hitchcock,14,8.5,8.007143,107.785714,2696577,2.337746e+09
470,Steven Spielberg,13,8.9,8.030769,141.923077,7817166,2.478133e+09
179,Hayao Miyazaki,11,8.6,8.018182,111.818182,2348718,2.447325e+09
313,Martin Scorsese,10,8.7,8.170000,145.100000,6513530,5.383192e+08
9,Akira Kurosawa,10,8.6,8.220000,137.800000,941599,3.070432e+09
...,...,...,...,...,...,...,...
506,Tony Bancroft,1,7.6,7.600000,88.000000,256906,1.206203e+08
512,Tyler Nilson,1,7.6,7.600000,97.000000,66346,1.312264e+07
521,Walter Hill,1,7.6,7.600000,92.000000,93878,2.249004e+07
531,Wolfgang Reitherman,1,7.6,7.600000,78.000000,166409,1.418436e+08
534,Yann Samuell,1,7.6,7.600000,93.000000,67360,5.487070e+05

In [11]:
director_analysis.head(20)

,Director,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
22,Alfred Hitchcock,14,8.5,8.007143,107.785714,2696577,2.337746e+09
470,Steven Spielberg,13,8.9,8.030769,141.923077,7817166,2.478133e+09
179,Hayao Miyazaki,11,8.6,8.018182,111.818182,2348718,2.447325e+09
313,Martin Scorsese,10,8.7,8.170000,145.100000,6513530,5.383192e+08
9,Akira Kurosawa,10,8.6,8.220000,137.800000,941599,3.070432e+09
49,Billy Wilder,9,8.4,8.144444,113.777778,1037903,1.557238e+09
463,Stanley Kubrick,9,8.4,8.233333,132.888889,3919254,1.047287e+09
532,Woody Allen,9,8.0,7.788889,96.222222,1222508,9.907487e+08
83,Christopher Nolan,8,9.0,8.462500,140.250000,11578345,1.937454e+09
391,Quentin Tarantino,8,8.9,8.175000,143.500000,8123208,7.270343e+08
100,David Fincher,8,8.8,8.037500,143.125000,6607859,7.133145e+08
84,Clint Eastwood,8,8.2,7.912500,133.500000,2683825,5.926926e+08
190,Ingmar Bergman,7,8.2,8.142857,105.571429,506073,1.654929e+09
413,Rob Reiner,7,8.1,7.828571,99.857143,1583349,3.805268e+08
187,Howard Hawks,7,8.0,7.857143,110.714286,328463,8.482779e+08
449,Sergio Leone,6,8.8,8.266667,157.166667,1763734,4.693971e+07
74,Charles Chaplin,6,8.5,8.333333,89.000000,833442,2.710727e+08
411,Ridley Scott,6,8.5,8.083333,139.000000,4339890,7.667114e+08
231,Joel Coen,6,8.1,7.816667,108.666667,1963613,1.010077e+08
408,Richard Linklater,6,8.1,7.900000,109.333333,1211741,5.573571e+07

In [12]:
experienced_directors=director_analysis[
    director_analysis["Movies"] >=3
    ].sort_values("Average_Rating",ascending=False)
experienced_directors.head(20)

,Director,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
137,Francis Ford Coppola,5,9.2,8.400000,159.800000,3815137,3.468240e+08
456,Sidney Lumet,5,9.0,8.100000,120.200000,1216445,8.215678e+08
83,Christopher Nolan,8,9.0,8.462500,140.250000,11578345,1.937454e+09
391,Quentin Tarantino,8,8.9,8.175000,143.500000,8123208,7.270343e+08
470,Steven Spielberg,13,8.9,8.030769,141.923077,7817166,2.478133e+09
383,Peter Jackson,5,8.9,8.400000,177.600000,6148579,1.597312e+09
426,Robert Zemeckis,5,8.8,8.120000,122.600000,4055464,1.049446e+09
449,Sergio Leone,6,8.8,8.266667,157.166667,1763734,4.693971e+07
100,David Fincher,8,8.8,8.037500,143.125000,6607859,7.133145e+08
313,Martin Scorsese,10,8.7,8.170000,145.100000,6513530,5.383192e+08
9,Akira Kurosawa,10,8.6,8.220000,137.800000,941599,3.070432e+09
179,Hayao Miyazaki,11,8.6,8.018182,111.818182,2348718,2.447325e+09
140,Frank Capra,4,8.6,8.200000,120.500000,671935,5.571983e+08
56,Bong Joon Ho,3,8.6,8.166667,130.666667,745094,5.392927e+07
411,Ridley Scott,6,8.5,8.083333,139.000000,4339890,7.667114e+08
74,Charles Chaplin,6,8.5,8.333333,89.000000,833442,2.710727e+08
22,Alfred Hitchcock,14,8.5,8.007143,107.785714,2696577,2.337746e+09
167,Giuseppe Tornatore,3,8.5,8.133333,151.666667,398182,1.233496e+07
64,Bryan Singer,3,8.5,8.133333,124.000000,2101320,4.736911e+08
431,Roman Polanski,5,8.5,8.000000,129.600000,1306279,7.918235e+08

In [13]:
top_director=director_analysis[(director_analysis["Movies"] >=3)&(director_analysis["Average_Rating"] >=7.5)
    ]
top_director

,Director,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
22,Alfred Hitchcock,14,8.5,8.007143,107.785714,2696577,2.337746e+09
470,Steven Spielberg,13,8.9,8.030769,141.923077,7817166,2.478133e+09
179,Hayao Miyazaki,11,8.6,8.018182,111.818182,2348718,2.447325e+09
313,Martin Scorsese,10,8.7,8.170000,145.100000,6513530,5.383192e+08
9,Akira Kurosawa,10,8.6,8.220000,137.800000,941599,3.070432e+09
...,...,...,...,...,...,...,...
213,James Whale,3,7.8,7.766667,72.000000,139566,3.667694e+08
227,Jim Jarmusch,3,7.8,7.733333,119.000000,193638,4.489657e+06
240,John Hughes,3,7.8,7.733333,97.666667,803181,1.655418e+08
485,Terrence Malick,3,7.8,7.733333,119.333333,291571,2.409641e+08
115,Don Siegel,3,7.7,7.666667,98.000000,309862,3.229008e+08

In [14]:
top_director.sort_values("Average_Rating",ascending=False)

,Director,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
137,Francis Ford Coppola,5,9.2,8.400000,159.800000,3815137,3.468240e+08
456,Sidney Lumet,5,9.0,8.100000,120.200000,1216445,8.215678e+08
83,Christopher Nolan,8,9.0,8.462500,140.250000,11578345,1.937454e+09
391,Quentin Tarantino,8,8.9,8.175000,143.500000,8123208,7.270343e+08
470,Steven Spielberg,13,8.9,8.030769,141.923077,7817166,2.478133e+09
...,...,...,...,...,...,...,...
213,James Whale,3,7.8,7.766667,72.000000,139566,3.667694e+08
485,Terrence Malick,3,7.8,7.733333,119.333333,291571,2.409641e+08
240,John Hughes,3,7.8,7.733333,97.666667,803181,1.655418e+08
320,Matthew Vaughn,4,7.7,7.650000,126.000000,2015069,3.613763e+08
115,Don Siegel,3,7.7,7.666667,98.000000,309862,3.229008e+08

In [15]:
best_director= director_analysis.loc[director_analysis["Average_Rating"].idxmax()]
best_director

Director           Frank Darabont
Movies                          2
Average_Rating                9.3
Highest_Rating               8.95
Average_Runtime             165.5
Total_Votes               3490904
Total_Gross           165142843.0
Name: 141, dtype: object

In [16]:
most_movies_director=director_analysis.loc[director_analysis["Movies"].idxmax()]
most_movies_director

Director           Alfred Hitchcock
Movies                           14
Average_Rating                  8.5
Highest_Rating             8.007143
Average_Runtime          107.785714
Total_Votes                 2696577
Total_Gross            2337745776.0
Name: 22, dtype: object

In [17]:
highest_gross_director=director_analysis.loc[director_analysis["Total_Gross"].idxmax()]
highest_gross_director

Director           Akira Kurosawa
Movies                         10
Average_Rating                8.6
Highest_Rating               8.22
Average_Runtime             137.8
Total_Votes                941599
Total_Gross          3070431739.0
Name: 9, dtype: object

In [18]:
director_groups=df.groupby("Director")

In [19]:
director_groups.get_group("Christopher Nolan")

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232
8,Inception,2010.0,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0,2067042
21,Interstellar,2014.0,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0,1512360
36,The Prestige,2006.0,130,Drama,8.5,Christopher Nolan,Christian Bale,1190259,53089891.0,66.0,1190259
63,The Dark Knight Rises,2012.0,164,Action,8.4,Christopher Nolan,Christian Bale,1516346,448139099.0,78.0,1516346
69,Memento,2000.0,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0,1125712
155,Batman Begins,2005.0,140,Action,8.2,Christopher Nolan,Christian Bale,1308302,206852432.0,70.0,1308302
573,Dunkirk,2017.0,106,Action,7.8,Christopher Nolan,Fionn Whitehead,555092,188373161.0,94.0,555092

In [20]:
director_filter= director_groups.filter(lambda x: len(x) >=3)
director_filter

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1620367
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,1129952
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,689845
5,The Lord of the Rings: The Return of the King,2003.0,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0,1642758
...,...,...,...,...,...,...,...,...,...,...,...
988,Close Encounters of the Third Kind,1977.0,138,Drama,7.6,Steven Spielberg,Richard Dreyfuss,184966,132088635.0,90.0,184966
990,Giù la testa,1971.0,157,Drama,7.6,Sergio Leone,Rod Steiger,30144,696690.0,77.0,30144
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,43374
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,26471
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,51853

In [21]:
director_mean_rating=director_groups["IMDB_Rating"].transform("mean")

In [22]:
df["Director_Average_Rating"]=director_mean_rating

In [23]:
print(
    df[[
        "Series_Title",
        "Director",
        "IMDB_Rating",
        "Director_Average_Rating"
    ]].sort_values(
        "Director_Average_Rating",
        ascending=False
    ).head(20)
)

                                       Series_Title            Director  \
0                          The Shawshank Redemption      Frank Darabont
25                                   The Green Mile      Frank Darabont
14                                       The Matrix      Lana Wachowski
16   Star Wars: Episode V - The Empire Strikes Back      Irvin Kershner
30                                          Seppuku    Masaki Kobayashi
22                                   Cidade de Deus  Fernando Meirelles
18                                         Hamilton         Thomas Kail
29                                        Star Wars        George Lucas
20                                  Soorarai Pottru       Sudha Kongara
26                                  La vita è bella     Roberto Benigni
43                                    The Lion King        Roger Allers
35                                 The Intouchables     Olivier Nakache
17                  One Flew Over the Cuckoo's Nest        Milos Forman
107                                         Amadeus        Milos Forman
155                                   Batman Begins   Christopher Nolan
36                                     The Prestige   Christopher Nolan
69                                          Memento   Christopher Nolan
2                                   The Dark Knight   Christopher Nolan
8                                         Inception   Christopher Nolan
21                                     Interstellar   Christopher Nolan

     IMDB_Rating  Director_Average_Rating
0            9.3                   8.9500
25           8.6                   8.9500
14           8.7                   8.7000
16           8.7                   8.7000
30           8.6                   8.6000
22           8.6                   8.6000
18           8.6                   8.6000
29           8.6                   8.6000
20           8.6                   8.6000
26           8.6                   8.6000
43           8.5                   8.5000
35           8.5                   8.5000
17           8.7                   8.5000
107          8.3                   8.5000
155          8.2                   8.4625
36           8.5                   8.4625
69           8.4                   8.4625
2            9.0                   8.4625
8            8.8                   8.4625
21           8.6                   8.4625

In [28]:
director_genre= df.groupby(
    ["Director","Genre"],
    as_index=False
).agg(
    Movies=("Series_Title","count"),
    Average_Rating=("IMDB_Rating","mean"),
    Total_Votes=("No_of_Votes","sum")
)
director_genre=director_genre.sort_values(
    ["Director","Average_Rating"],
    ascending=[True,False]
               )
director_genre.head(30)

                 Director      Genre  Movies  Average_Rating  Total_Votes
0              Aamir Khan      Drama       1        8.400000       168895
1            Aaron Sorkin      Drama       1        7.800000        89896
2     Abdellatif Kechiche      Drama       1        7.700000       138741
3        Abhishek Chaubey     Action       1        7.800000        27175
4         Abhishek Kapoor      Drama       1        7.700000        32628
5             Adam Elliot  Animation       1        8.100000       164462
6              Adam McKay  Biography       1        7.800000       362942
7           Aditya Chopra      Drama       1        8.100000        63516
8             Aditya Dhar     Action       1        8.200000        43444
11         Akira Kurosawa      Crime       2        8.300000       186929
9          Akira Kurosawa     Action       4        8.275000       572537
12         Akira Kurosawa      Drama       3        8.133333       147336
10         Akira Kurosawa  Adventure       1        8.100000        34797
13          Alain Resnais      Drama       1        7.900000        28421
14         Alan J. Pakula  Biography       1        7.900000       103031
17            Alan Parker      Drama       1        8.100000        76081
16            Alan Parker      Crime       1        7.800000        88214
15            Alan Parker  Biography       1        7.600000        73662
18     Alejandro Amenábar  Biography       1        8.000000        77554
19     Alejandro Amenábar      Drama       1        7.700000        64082
20     Alejandro Amenábar     Horror       1        7.600000       337651
24  Alejandro G. Iñárritu      Drama       1        8.100000       223741
21  Alejandro G. Iñárritu     Action       1        8.000000       705589
22  Alejandro G. Iñárritu     Comedy       1        7.700000       580291
23  Alejandro G. Iñárritu      Crime       1        7.600000       224545
25   Alejandro Jodorowsky  Adventure       1        7.900000        37183
26           Alex Garland      Drama       1        7.700000       474141
27            Alex Proyas    Mystery       1        7.600000       187927
29  Alexander Mackendrick      Drama       1        8.000000        28137
28  Alexander Mackendrick     Comedy       1        7.700000        26464

In [32]:
star_analysis=df.groupby("Star1",as_index=False).agg(
     Movies=("Series_Title","count"),
    Average_Rating=("IMDB_Rating","mean"),
    Highest_Rating=("IMDB_Rating","max"),
    Total_Votes=("No_of_Votes","sum") 
    )
star_analysis=star_analysis[
       star_analysis["Movies"] >=3
       ].sort_values(
       "Average_Rating",
 ascending=False
 )
star_analysis.head(20)

,Star1,Movies,Average_Rating,Highest_Rating,Total_Votes
184,Elijah Wood,3,8.800000,8.9,4789794
414,Mark Hamill,3,8.533333,8.7,3341258
252,Henry Fonda,3,8.500000,9.0,1078248
111,Charles Chaplin,6,8.333333,8.5,833442
358,Kevin Spacey,3,8.333333,8.5,2592913
591,Tatsuya Nakadai,3,8.266667,8.6,186704
612,Toshirô Mifune,7,8.242857,8.6,728436
273,Jack Nicholson,4,8.225000,8.7,2386310
0,Aamir Khan,7,8.214286,8.4,997061
282,James Stewart,8,8.175000,8.6,1632290
382,Leonardo DiCaprio,9,8.133333,8.8,9209479
362,Kirk Douglas,3,8.133333,8.4,333999
426,Matthew McConaughey,3,8.133333,8.6,2191366
80,Brad Pitt,4,8.125000,8.8,4081298
128,Christian Bale,8,8.112500,9.0,7645252
249,Harrison Ford,5,8.100000,8.4,2999812
45,Arnold Schwarzenegger,3,8.100000,8.5,2166688
343,Kang-ho Song,3,8.100000,8.6,754995
638,William Holden,4,8.100000,8.4,533542
311,Joaquin Phoenix,3,8.100000,8.5,1714231

In [35]:
director_status=df.groupby("Director").agg(
     Movies=("Series_Title","count"),
    Average_Rating=("IMDB_Rating","mean")
)
director_status["Rating_Rank"]=director_status["Average_Rating"].rank(ascending=False,method="dense")
director_status.sort_values("Rating_Rank").head(20)

                                  Movies  Average_Rating  Rating_Rank
Director
Frank Darabont                         2          8.9500          1.0
Lana Wachowski                         1          8.7000          2.0
Irvin Kershner                         1          8.7000          2.0
Sudha Kongara                          1          8.6000          3.0
Roberto Benigni                        1          8.6000          3.0
Fernando Meirelles                     1          8.6000          3.0
George Lucas                           1          8.6000          3.0
Thomas Kail                            1          8.6000          3.0
Masaki Kobayashi                       1          8.6000          3.0
Olivier Nakache                        1          8.5000          4.0
Roger Allers                           1          8.5000          4.0
Milos Forman                           2          8.5000          4.0
Christopher Nolan                      8          8.4625          5.0
Can Ulkay                              1          8.4000          6.0
Makoto Shinkai                         1          8.4000          6.0
Florian Henckel von Donnersmarck       1          8.4000          6.0
Gayatri                                1          8.4000          6.0
Peter Jackson                          5          8.4000          6.0
Hrishikesh Mukherjee                   1          8.4000          6.0
Francis Ford Coppola                   5          8.4000          6.0