# Pandas GroupBy - Big Programe 1

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("imdb-top-1000.csv.xls")

In [3]:
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [4]:
df["Released_Year"]=pd.to_numeric(df["Released_Year"],errors="coerce")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [5]:
df["IMDB_Rating"]=pd.to_numeric(df["IMDB_Rating"],errors="coerce")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [6]:
df["No_of_Votes	"]=pd.to_numeric(df["No_of_Votes"],errors="coerce")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,2343110
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1620367
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,1129952
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,689845
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,166544
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,34075
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,43374
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,26471
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,51853

In [7]:
df["Gross"]=pd.to_numeric(df["Gross"],errors="coerce")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,2343110
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1620367
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,1129952
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,689845
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,166544
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,34075
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,43374
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,26471
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,51853

In [8]:
df["Metascore"]=pd.to_numeric(df["Metascore"],errors="coerce")
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,2343110
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1620367
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,1129952
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,689845
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,166544
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,34075
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,43374
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,26471
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,51853

In [9]:
df["Decade"]=(df["Released_Year"]//10)*10
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t,Decade
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,2343110,1990.0
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1620367,1970.0
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232,2000.0
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,1129952,1970.0
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,689845,1950.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,166544,1960.0
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,34075,1950.0
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,43374,1950.0
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,26471,1940.0
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,51853,1930.0

In [10]:
genre_count=df.groupby("Genre").size().sort_values(ascending=False)
genre_count

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Family         2
Fantasy        2
Thriller       1
dtype: int64

In [11]:
genre_rating=df.groupby("Genre")["IMDB_Rating"].sum().sort_values(ascending=False)
genre_rating

Genre
Drama        2299.7
Action       1367.3
Comedy       1224.7
Crime         857.8
Biography     698.6
Animation     650.3
Adventure     571.5
Mystery        95.7
Horror         87.0
Western        33.4
Film-Noir      23.9
Fantasy        16.0
Family         15.6
Thriller        7.8
Name: IMDB_Rating, dtype: float64

In [12]:
genre_analysis=df.groupby("Genre",as_index=False).agg(
    Movies=("Series_Title","count"),
    Average_Rating=("IMDB_Rating","max"),
    Highest_Rating=("IMDB_Rating","mean"),
    Average_Runtime=("Runtime","mean"),
    Total_Votes=("No_of_Votes","sum"),
    Total_Gross=("Gross","sum")
    )
genre_analysis

,Genre,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
0,Action,172,9.0,7.949419,129.046512,72282412,3.263226e+10
1,Adventure,72,8.6,7.937500,134.111111,22576163,9.496922e+09
2,Animation,82,8.6,7.930488,99.585366,21978630,1.463147e+10
3,Biography,88,8.9,7.938636,136.022727,24006844,8.276358e+09
4,Comedy,155,8.6,7.901290,112.129032,27620327,1.566387e+10
5,Crime,107,9.2,8.016822,126.392523,33533615,8.452632e+09
6,Drama,289,9.3,7.957439,124.737024,61367304,3.540997e+10
7,Family,2,7.8,7.800000,107.500000,551221,4.391106e+08
8,Fantasy,2,8.1,8.000000,85.000000,146222,7.827267e+08
9,Film-Noir,3,8.1,7.966667,104.000000,367215,1.259105e+08
10,Horror,11,8.5,7.909091,102.090909,3742556,1.034649e+09
11,Mystery,12,8.4,7.975000,119.083333,4203004,1.256417e+09
12,Thriller,1,7.8,7.800000,108.000000,27733,1.755074e+07
13,Western,4,8.8,8.350000,148.250000,1289665,5.822151e+07

In [13]:
genre_analysis=genre_analysis.sort_values("Average_Rating",ascending=False)
genre_analysis

,Genre,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
6,Drama,289,9.3,7.957439,124.737024,61367304,3.540997e+10
5,Crime,107,9.2,8.016822,126.392523,33533615,8.452632e+09
0,Action,172,9.0,7.949419,129.046512,72282412,3.263226e+10
3,Biography,88,8.9,7.938636,136.022727,24006844,8.276358e+09
13,Western,4,8.8,8.350000,148.250000,1289665,5.822151e+07
1,Adventure,72,8.6,7.937500,134.111111,22576163,9.496922e+09
4,Comedy,155,8.6,7.901290,112.129032,27620327,1.566387e+10
2,Animation,82,8.6,7.930488,99.585366,21978630,1.463147e+10
10,Horror,11,8.5,7.909091,102.090909,3742556,1.034649e+09
11,Mystery,12,8.4,7.975000,119.083333,4203004,1.256417e+09
8,Fantasy,2,8.1,8.000000,85.000000,146222,7.827267e+08
9,Film-Noir,3,8.1,7.966667,104.000000,367215,1.259105e+08
7,Family,2,7.8,7.800000,107.500000,551221,4.391106e+08
12,Thriller,1,7.8,7.800000,108.000000,27733,1.755074e+07

In [14]:
popular_genres=genre_analysis[genre_analysis["Movies"] >=20]
popular_genres

,Genre,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
6,Drama,289,9.3,7.957439,124.737024,61367304,3.540997e+10
5,Crime,107,9.2,8.016822,126.392523,33533615,8.452632e+09
0,Action,172,9.0,7.949419,129.046512,72282412,3.263226e+10
3,Biography,88,8.9,7.938636,136.022727,24006844,8.276358e+09
1,Adventure,72,8.6,7.937500,134.111111,22576163,9.496922e+09
4,Comedy,155,8.6,7.901290,112.129032,27620327,1.566387e+10
2,Animation,82,8.6,7.930488,99.585366,21978630,1.463147e+10

In [15]:
high_rated_genre=genre_analysis[(genre_analysis["Movies"] >=10)&(genre_analysis["Average_Rating"] >=7.5)
    ]
high_rated_genre

,Genre,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
6,Drama,289,9.3,7.957439,124.737024,61367304,3.540997e+10
5,Crime,107,9.2,8.016822,126.392523,33533615,8.452632e+09
0,Action,172,9.0,7.949419,129.046512,72282412,3.263226e+10
3,Biography,88,8.9,7.938636,136.022727,24006844,8.276358e+09
1,Adventure,72,8.6,7.937500,134.111111,22576163,9.496922e+09
4,Comedy,155,8.6,7.901290,112.129032,27620327,1.566387e+10
2,Animation,82,8.6,7.930488,99.585366,21978630,1.463147e+10
10,Horror,11,8.5,7.909091,102.090909,3742556,1.034649e+09
11,Mystery,12,8.4,7.975000,119.083333,4203004,1.256417e+09

In [16]:
best_genre=genre_analysis.loc[genre_analysis["Average_Rating"].idxmax()]
best_genre

Genre                      Drama
Movies                       289
Average_Rating               9.3
Highest_Rating          7.957439
Average_Runtime       124.737024
Total_Votes             61367304
Total_Gross        35409974041.0
Name: 6, dtype: object

In [29]:
most_movies_genre=genre_analysis.loc[genre_analysis["Movies"].idxmin()]
most_movies_genre

Genre                Thriller
Movies                      1
Average_Rating            7.8
Highest_Rating            7.8
Average_Runtime         108.0
Total_Votes             27733
Total_Gross        17550741.0
Name: 12, dtype: object

In [18]:
highest_gross_genre=genre_analysis.loc[genre_analysis["Total_Gross"].idxmax()]
highest_gross_genre

Genre                      Drama
Movies                       289
Average_Rating               9.3
Highest_Rating          7.957439
Average_Runtime       124.737024
Total_Votes             61367304
Total_Gross        35409974041.0
Name: 6, dtype: object

In [19]:
decade_analysis=df.groupby("Decade",as_index=False).agg(
     Movies=("Series_Title","count"),
    Average_Rating=("IMDB_Rating","max"),
    Highest_Rating=("IMDB_Rating","mean"),
    Average_Runtime=("Runtime","mean"),
    Total_Votes=("No_of_Votes","sum"),
    Total_Gross=("Gross","sum")
    )
decade_analysis

,Decade,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
0,1920.0,11,8.3,8.127273,86.272727,821522,1.057188e+09
1,1930.0,24,8.5,7.966667,102.125000,2153513,3.278170e+09
2,1940.0,35,8.6,8.025714,109.800000,3635044,5.718223e+09
3,1950.0,56,9.0,8.058929,118.678571,6624103,1.088733e+10
4,1960.0,73,8.8,7.973973,126.452055,8946462,1.575554e+10
5,1970.0,76,9.2,7.969737,122.736842,15793649,1.135531e+10
6,1980.0,89,8.7,7.953933,121.224719,23197061,8.992581e+09
7,1990.0,150,9.3,7.963333,123.613333,53265043,1.273299e+10
8,2000.0,237,9.0,7.899578,123.607595,82101940,2.320710e+10
9,2010.0,242,8.8,7.924380,127.756198,76380615,3.236852e+10
10,2020.0,6,8.6,8.133333,126.666667,504762,2.751280e+09

In [20]:
decade_analysis=decade_analysis.sort_values("Decade")
decade_analysis

,Decade,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
0,1920.0,11,8.3,8.127273,86.272727,821522,1.057188e+09
1,1930.0,24,8.5,7.966667,102.125000,2153513,3.278170e+09
2,1940.0,35,8.6,8.025714,109.800000,3635044,5.718223e+09
3,1950.0,56,9.0,8.058929,118.678571,6624103,1.088733e+10
4,1960.0,73,8.8,7.973973,126.452055,8946462,1.575554e+10
5,1970.0,76,9.2,7.969737,122.736842,15793649,1.135531e+10
6,1980.0,89,8.7,7.953933,121.224719,23197061,8.992581e+09
7,1990.0,150,9.3,7.963333,123.613333,53265043,1.273299e+10
8,2000.0,237,9.0,7.899578,123.607595,82101940,2.320710e+10
9,2010.0,242,8.8,7.924380,127.756198,76380615,3.236852e+10
10,2020.0,6,8.6,8.133333,126.666667,504762,2.751280e+09

In [21]:
top_decade=decade_analysis.sort_values("Average_Rating",ascending=False).head(5)
top_decade

,Decade,Movies,Average_Rating,Highest_Rating,Average_Runtime,Total_Votes,Total_Gross
7,1990.0,150,9.3,7.963333,123.613333,53265043,1.273299e+10
5,1970.0,76,9.2,7.969737,122.736842,15793649,1.135531e+10
8,2000.0,237,9.0,7.899578,123.607595,82101940,2.320710e+10
3,1950.0,56,9.0,8.058929,118.678571,6624103,1.088733e+10
9,2010.0,242,8.8,7.924380,127.756198,76380615,3.236852e+10

In [31]:
genre_groups=df.groupby("Genre")
genre_groups.size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [23]:
genre_groups.get_group("Drama").head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t,Decade
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,2343110,1990.0
9,Fight Club,1999.0,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0,1854740,1990.0
11,Forrest Gump,1994.0,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182.0,82.0,1809221,1990.0
17,One Flew Over the Cuckoo's Nest,1975.0,133,Drama,8.7,Milos Forman,Jack Nicholson,918088,112000000.0,83.0,918088,1970.0
20,Soorarai Pottru,2020.0,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN,54995,2020.0

In [30]:
genre_groups["IMDB_Rating"].head(3)

0      9.3
1      9.2
2      9.0
3      9.0
4      9.0
5      8.9
7      8.9
8      8.8
9      8.8
11     8.8
12     8.8
15     8.7
18     8.6
19     8.6
21     8.6
23     8.6
26     8.6
43     8.5
46     8.5
47     8.5
48     8.5
49     8.5
51     8.5
69     8.4
75     8.4
81     8.4
93     8.3
115    8.3
119    8.3
271    8.1
309    8.1
321    8.1
456    8.0
568    7.9
688    7.8
698    7.8
700    7.8
712    7.8
Name: IMDB_Rating, dtype: float64

In [25]:
genre_filter=genre_groups.filter(lambda x: len(x) >=20)
genre_filter

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t,Decade
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,2343110,1990.0
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1620367,1970.0
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232,2000.0
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,1129952,1970.0
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,689845,1950.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,166544,1960.0
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,34075,1950.0
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,43374,1950.0
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,26471,1940.0
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,51853,1930.0

In [33]:
genre_mean_rating=genre_groups["IMDB_Rating"].transform("mean")
df["Genre_Mean_Rating"]=genre_mean_rating
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,No_of_Votes\t,Decade,Genre_Mean_Rating
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,2343110,1990.0,7.957439
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1620367,1970.0,8.016822
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,2303232,2000.0,7.949419
3,The Godfather: Part II,1974.0,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,1129952,1970.0,8.016822
4,12 Angry Men,1957.0,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,689845,1950.0,8.016822
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961.0,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,166544,1960.0,7.901290
996,Giant,1956.0,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,34075,1950.0,7.957439
997,From Here to Eternity,1953.0,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,43374,1950.0,7.957439
998,Lifeboat,1944.0,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,26471,1940.0,7.957439
999,The 39 Steps,1935.0,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,51853,1930.0,8.016822

In [35]:

df[["Series_Title","Genre","IMDB_Rating","Genre_Mean_Rating"]].sort_values("Genre_Mean_Rating",ascending=False).head(20)

                        Series_Title    Genre  IMDB_Rating  Genre_Mean_Rating
12   Il buono, il brutto, il cattivo  Western          8.8           8.350000
115       Per qualche dollaro in più  Western          8.3           8.350000
691           The Outlaw Josey Wales  Western          7.8           8.350000
48      Once Upon a Time in the West  Western          8.5           8.350000
187                Dial M for Murder    Crime          8.2           8.016822
25                    The Green Mile    Crime          8.6           8.016822
37                      The Departed    Crime          8.5           8.016822
827                Miller's Crossing    Crime          7.7           8.016822
974          The Godfather: Part III    Crime          7.6           8.016822
833                Der Name der Rose    Crime          7.7           8.016822
136                         Drishyam    Crime          8.2           8.016822
189                         Rashômon    Crime          8.2           8.016822
775                            Crash    Crime          7.7           8.016822
708                À bout de souffle    Crime          7.8           8.016822
980                     Blood Simple    Crime          7.6           8.016822
895                         Leviafan    Crime          7.6           8.016822
4                       12 Angry Men    Crime          9.0           8.016822
71       Once Upon a Time in America    Crime          8.4           8.016822
3             The Godfather: Part II    Crime          9.0           8.016822
6                       Pulp Fiction    Crime          8.9           8.016822