# Pandas Merge-Program 1

In [1]:
import pandas as pd

In [2]:
students=pd.read_csv("students.csv.xls")
students.tail(2)

    student_id             name  partner
23          24     Radhika Suri       17
24          25  Shashank D’Alia        2

In [3]:
courses=pd.read_csv("courses.csv.xls")
courses.head(2)

   course_id course_name  price
0          1      python   2499
1          2         sql   3499

**Q1.Students aur courses ko course_id ke basis par merge registration details ka Dataframe banao.**

**Answer:**

In [1]:
reg=pd.read_csv("reg-month1.csv.xls")
result=pd.merge(reg,students, on="student_id", how="inner")
result
result=pd.merge(result,courses, on="course_id", how="inner")
result

NameError: name 'pd' is not defined

**Q2. students aur month 1 registrations ki inner merge karo**

**Answer:**

In [5]:
students.head()

   student_id            name  partner
0           1   Kailash Harjo       23
1           2     Esha Butala        1
2           3  Parveen Bhalla        3
3           4     Marlo Dugal       14
4           5     Kusum Bahri        6

In [6]:
reg.head()

   student_id  course_id
0          23          1
1          15          5
2          18          6
3          23          4
4          16          9

In [7]:
inner_result=pd.merge(
    students,
    reg,
    on="student_id",
    how="inner"
)
inner_result

    student_id                name  partner  course_id
0           15           Preet Sha       16          5
1           19        Qabeel Raman       12          4
2           22          Yash Sethi       21          3
3           19        Qabeel Raman       12          2
4           11  David Mukhopadhyay       20          7
5           13      Munni Varghese       24          3
6           15           Preet Sha       16          1
7           24        Radhika Suri       17          4
8           21          Seema Kota       15          1
9           17        Yasmin Palan        7          7
10          16        Elias Dodiya       25          9
11          25     Shashank D’Alia        2          1
12          16        Elias Dodiya       25          5
13          25     Shashank D’Alia        2         10
14          23      Chhavi Lachman       18          4
15          23      Chhavi Lachman       18          6
16           7        Tarun Thaker        9          8
17          23      Chhavi Lachman       18          3
18          18     Fardeen Mahabir       13          1
19           3      Parveen Bhalla        3          3
20           1       Kailash Harjo       23          6
21          18     Fardeen Mahabir       13          6
22          23      Chhavi Lachman       18          1
23           1       Kailash Harjo       23          1
24           7        Tarun Thaker        9         10

**Q3. students aur month 1 registrations ko left merge karo.**

**Answer:**

In [8]:
left_result=pd.merge(
    students,
    reg,
    on="student_id",
    how="left"
)
left_result

    student_id                name  partner  course_id
0            1       Kailash Harjo       23        1.0
1            1       Kailash Harjo       23        6.0
2            2         Esha Butala        1        NaN
3            3      Parveen Bhalla        3        3.0
4            4         Marlo Dugal       14        NaN
5            5         Kusum Bahri        6        NaN
6            6  Lakshmi Contractor       10        NaN
7            7        Tarun Thaker        9        8.0
8            7        Tarun Thaker        9       10.0
9            8      Radheshyam Dey        5        NaN
10           9   Nitika Chatterjee        4        NaN
11          10      Aayushman Sant        8        NaN
12          11  David Mukhopadhyay       20        7.0
13          12          Radha Dutt       19        NaN
14          13      Munni Varghese       24        3.0
15          14    Pranab Natarajan       22        NaN
16          15           Preet Sha       16        5.0
17          15           Preet Sha       16        1.0
18          16        Elias Dodiya       25        9.0
19          16        Elias Dodiya       25        5.0
20          17        Yasmin Palan        7        7.0
21          18     Fardeen Mahabir       13        6.0
22          18     Fardeen Mahabir       13        1.0
23          19        Qabeel Raman       12        4.0
24          19        Qabeel Raman       12        2.0
25          20       Hanuman Hegde       11        NaN
26          21          Seema Kota       15        1.0
27          22          Yash Sethi       21        3.0
28          23      Chhavi Lachman       18        1.0
29          23      Chhavi Lachman       18        4.0
30          23      Chhavi Lachman       18        3.0
31          23      Chhavi Lachman       18        6.0
32          24        Radhika Suri       17        4.0
33          25     Shashank D’Alia        2        1.0
34          25     Shashank D’Alia        2       10.0

**Q4. Month 1 registration aur courses ko course_id par merge karke course name aur price add karo.**

**Answer:**

In [9]:
reg.head()

   student_id  course_id
0          23          1
1          15          5
2          18          6
3          23          4
4          16          9

In [10]:
courses.head()

   course_id       course_name  price
0          1            python   2499
1          2               sql   3499
2          3     data analysis   4999
3          4  machine learning   9999
4          5           tableau   2499

In [11]:
course_result=pd.merge(
    reg,
    courses,
    on="course_id",
    how="inner"
)
course_result
A=pd.merge(course_result,students,on='student_id',how='inner')
A

,student_id,course_id,course_name,price,name,partner
0,23,1,python,2499,Chhavi Lachman,18
1,15,5,tableau,2499,Preet Sha,16
2,18,6,power bi,1899,Fardeen Mahabir,13
3,23,4,machine learning,9999,Chhavi Lachman,18
4,16,9,plotly,699,Elias Dodiya,25
5,18,1,python,2499,Fardeen Mahabir,13
6,1,1,python,2499,Kailash Harjo,23
7,7,8,pandas,1099,Tarun Thaker,9
8,22,3,data analysis,4999,Yash Sethi,21
9,15,1,python,2499,Preet Sha,16
10,19,4,machine learning,9999,Qabeel Raman,12
11,1,6,power bi,1899,Kailash Harjo,23
12,7,10,pyspark,2499,Tarun Thaker,9
13,11,7,ms sxcel,1599,David Mukhopadhyay,20
14,13,3,data analysis,4999,Munni Varghese,24
15,24,4,machine learning,9999,Radhika Suri,17
16,21,1,python,2499,Seema Kota,15
17,16,5,tableau,2499,Elias Dodiya,25
18,23,3,data analysis,4999,Chhavi Lachman,18
19,17,7,ms sxcel,1599,Yasmin Palan,7
20,23,6,power bi,1899,Chhavi Lachman,18
21,25,1,python,2499,Shashank D’Alia,2
22,19,2,sql,3499,Qabeel Raman,12
23,25,10,pyspark,2499,Shashank D’Alia,2
24,3,3,data analysis,4999,Parveen Bhalla,3

**Q5. students ke saath courses ki complete information add karke final table banao.**

**Answer:**

In [12]:
final_result=pd.merge(
    inner_result,
    courses,
    on="course_id",
    how="left"
)
final_result

,student_id,name,partner,course_id,course_name,price
0,15,Preet Sha,16,5,tableau,2499
1,19,Qabeel Raman,12,4,machine learning,9999
2,22,Yash Sethi,21,3,data analysis,4999
3,19,Qabeel Raman,12,2,sql,3499
4,11,David Mukhopadhyay,20,7,ms sxcel,1599
5,13,Munni Varghese,24,3,data analysis,4999
6,15,Preet Sha,16,1,python,2499
7,24,Radhika Suri,17,4,machine learning,9999
8,21,Seema Kota,15,1,python,2499
9,17,Yasmin Palan,7,7,ms sxcel,1599
10,16,Elias Dodiya,25,9,plotly,699
11,25,Shashank D’Alia,2,1,python,2499
12,16,Elias Dodiya,25,5,tableau,2499
13,25,Shashank D’Alia,2,10,pyspark,2499
14,23,Chhavi Lachman,18,4,machine learning,9999
15,23,Chhavi Lachman,18,6,power bi,1899
16,7,Tarun Thaker,9,8,pandas,1099
17,23,Chhavi Lachman,18,3,data analysis,4999
18,18,Fardeen Mahabir,13,1,python,2499
19,3,Parveen Bhalla,3,3,data analysis,4999
20,1,Kailash Harjo,23,6,power bi,1899
21,18,Fardeen Mahabir,13,6,power bi,1899
22,23,Chhavi Lachman,18,1,python,2499
23,1,Kailash Harjo,23,1,python,2499
24,7,Tarun Thaker,9,10,pyspark,2499

**Q6.har course ki registration count aur total revenue nikalo.**

**Answer:**

In [13]:
summary=final_result.groupby("course_name").agg(
    registrations=("student_id","count"),
    total_revenue=("price","sum")
).sort_values("registrations",ascending=False)
summary

                  registrations  total_revenue
course_name
python                        6          14994
data analysis                 4          19996
machine learning              3          29997
power bi                      3           5697
pyspark                       2           4998
ms sxcel                      2           3198
tableau                       2           4998
pandas                        1           1099
plotly                        1            699
sql                           1           3499

In [14]:
summary=final_result.groupby("course_name").agg(
       registrations=("student_id","count"))
summary

                  registrations
course_name
data analysis                 4
machine learning              3
ms sxcel                      2
pandas                        1
plotly                        1
power bi                      3
pyspark                       2
python                        6
sql                           1
tableau                       2