# Pandas Merge-Program 2

In [1]:
import pandas as pd

In [2]:
students=pd.read_csv("students.csv.xls")

In [3]:
month1=pd.read_csv("reg-month1.csv.xls")

In [4]:
month2=pd.read_csv("reg-month2.csv.xls")

In [5]:
courses=pd.read_csv("courses.csv.xls")

**Q1. Month 1 aur Month 2 registrations ko students dadaset ke sasth merge karke dono ka complete student data banao.**

**Answer:**

In [6]:
students.head()

   student_id            name  partner
0           1   Kailash Harjo       23
1           2     Esha Butala        1
2           3  Parveen Bhalla        3
3           4     Marlo Dugal       14
4           5     Kusum Bahri        6

In [7]:
month1.head()

   student_id  course_id
0          23          1
1          15          5
2          18          6
3          23          4
4          16          9

In [8]:
month2.head()

   student_id  course_id
0           3          5
1          16          7
2          12         10
3          12          1
4          14          9

In [9]:
courses.head()

   course_id       course_name  price
0          1            python   2499
1          2               sql   3499
2          3     data analysis   4999
3          4  machine learning   9999
4          5           tableau   2499

In [10]:
m1=pd.merge(
    month1,
    students,
    on="student_id",
    how="inner"
)
m1

    student_id  course_id                name  partner
0           23          1      Chhavi Lachman       18
1           15          5           Preet Sha       16
2           18          6     Fardeen Mahabir       13
3           23          4      Chhavi Lachman       18
4           16          9        Elias Dodiya       25
5           18          1     Fardeen Mahabir       13
6            1          1       Kailash Harjo       23
7            7          8        Tarun Thaker        9
8           22          3          Yash Sethi       21
9           15          1           Preet Sha       16
10          19          4        Qabeel Raman       12
11           1          6       Kailash Harjo       23
12           7         10        Tarun Thaker        9
13          11          7  David Mukhopadhyay       20
14          13          3      Munni Varghese       24
15          24          4        Radhika Suri       17
16          21          1          Seema Kota       15
17          16          5        Elias Dodiya       25
18          23          3      Chhavi Lachman       18
19          17          7        Yasmin Palan        7
20          23          6      Chhavi Lachman       18
21          25          1     Shashank D’Alia        2
22          19          2        Qabeel Raman       12
23          25         10     Shashank D’Alia        2
24           3          3      Parveen Bhalla        3

In [11]:
m2=pd.merge(
    month2,
    students,
    on="student_id",
    how="inner"
)
m2

    student_id  course_id                name  partner
0            3          5      Parveen Bhalla        3
1           16          7        Elias Dodiya       25
2           12         10          Radha Dutt       19
3           12          1          Radha Dutt       19
4           14          9    Pranab Natarajan       22
5            7          7        Tarun Thaker        9
6            7          2        Tarun Thaker        9
7           16          3        Elias Dodiya       25
8           17         10        Yasmin Palan        7
9           11          8  David Mukhopadhyay       20
10          14          6    Pranab Natarajan       22
11          12          5          Radha Dutt       19
12          12          7          Radha Dutt       19
13          18          8     Fardeen Mahabir       13
14           1         10       Kailash Harjo       23
15           1          9       Kailash Harjo       23
16           2          5         Esha Butala        1
17           7          6        Tarun Thaker        9
18          22          5          Yash Sethi       21
19          22          6          Yash Sethi       21
20          23          9      Chhavi Lachman       18
21          23          5      Chhavi Lachman       18
22          14          4    Pranab Natarajan       22
23          14          1    Pranab Natarajan       22
24          11         10  David Mukhopadhyay       20

In [12]:
m2=pd.merge(
    m1,
    month2,
    on="student_id",
    how="inner"
)
m2

    student_id  course_id_x                name  partner  course_id_y
0           23            1      Chhavi Lachman       18            9
1           23            1      Chhavi Lachman       18            5
2           18            6     Fardeen Mahabir       13            8
3           23            4      Chhavi Lachman       18            9
4           23            4      Chhavi Lachman       18            5
5           16            9        Elias Dodiya       25            7
6           16            9        Elias Dodiya       25            3
7           18            1     Fardeen Mahabir       13            8
8            1            1       Kailash Harjo       23           10
9            1            1       Kailash Harjo       23            9
10           7            8        Tarun Thaker        9            7
11           7            8        Tarun Thaker        9            2
12           7            8        Tarun Thaker        9            6
13          22            3          Yash Sethi       21            5
14          22            3          Yash Sethi       21            6
15           1            6       Kailash Harjo       23           10
16           1            6       Kailash Harjo       23            9
17           7           10        Tarun Thaker        9            7
18           7           10        Tarun Thaker        9            2
19           7           10        Tarun Thaker        9            6
20          11            7  David Mukhopadhyay       20            8
21          11            7  David Mukhopadhyay       20           10
22          16            5        Elias Dodiya       25            7
23          16            5        Elias Dodiya       25            3
24          23            3      Chhavi Lachman       18            9
25          23            3      Chhavi Lachman       18            5
26          17            7        Yasmin Palan        7           10
27          23            6      Chhavi Lachman       18            9
28          23            6      Chhavi Lachman       18            5
29           3            3      Parveen Bhalla        3            5

In [13]:
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

**Q2. Month 2 ke data ko courses ke sath merge karke course ka name aur price add karo.**

**Answer:**

In [14]:
m2_course=pd.merge(
    month2,
    courses,
    on="course_id",
    how="inner"
)
m2_course

    student_id  course_id       course_name  price
0            3          5           tableau   2499
1           16          7          ms sxcel   1599
2           12         10           pyspark   2499
3           12          1            python   2499
4           14          9            plotly    699
5            7          7          ms sxcel   1599
6            7          2               sql   3499
7           16          3     data analysis   4999
8           17         10           pyspark   2499
9           11          8            pandas   1099
10          14          6          power bi   1899
11          12          5           tableau   2499
12          12          7          ms sxcel   1599
13          18          8            pandas   1099
14           1         10           pyspark   2499
15           1          9            plotly    699
16           2          5           tableau   2499
17           7          6          power bi   1899
18          22          5           tableau   2499
19          22          6          power bi   1899
20          23          9            plotly    699
21          23          5           tableau   2499
22          14          4  machine learning   9999
23          14          1            python   2499
24          11         10           pyspark   2499
25          42          9            plotly    699
26          50          8            pandas   1099
27          38          1            python   2499

**Q3. month 1 ke data ko courses ke sath merge karke course ka name aur price add karo.**

**Answer:**

In [15]:
m1_course=pd.merge(
     month1,
    courses,
    on="course_id",
    how="inner"
)
m1_course

    student_id  course_id       course_name  price
0           23          1            python   2499
1           15          5           tableau   2499
2           18          6          power bi   1899
3           23          4  machine learning   9999
4           16          9            plotly    699
5           18          1            python   2499
6            1          1            python   2499
7            7          8            pandas   1099
8           22          3     data analysis   4999
9           15          1            python   2499
10          19          4  machine learning   9999
11           1          6          power bi   1899
12           7         10           pyspark   2499
13          11          7          ms sxcel   1599
14          13          3     data analysis   4999
15          24          4  machine learning   9999
16          21          1            python   2499
17          16          5           tableau   2499
18          23          3     data analysis   4999
19          17          7          ms sxcel   1599
20          23          6          power bi   1899
21          25          1            python   2499
22          19          2               sql   3499
23          25         10           pyspark   2499
24           3          3     data analysis   4999

**Q4. dono months ke merged data ko ek single DataFrame me combine karo.**

**Answer:**

In [21]:
final=pd.concat(
    [m1_course,m2_course],
    ignore_index=True
)
final

    student_id  course_id       course_name  price
0           23          1            python   2499
1           15          5           tableau   2499
2           18          6          power bi   1899
3           23          4  machine learning   9999
4           16          9            plotly    699
5           18          1            python   2499
6            1          1            python   2499
7            7          8            pandas   1099
8           22          3     data analysis   4999
9           15          1            python   2499
10          19          4  machine learning   9999
11           1          6          power bi   1899
12           7         10           pyspark   2499
13          11          7          ms sxcel   1599
14          13          3     data analysis   4999
15          24          4  machine learning   9999
16          21          1            python   2499
17          16          5           tableau   2499
18          23          3     data analysis   4999
19          17          7          ms sxcel   1599
20          23          6          power bi   1899
21          25          1            python   2499
22          19          2               sql   3499
23          25         10           pyspark   2499
24           3          3     data analysis   4999
25           3          5           tableau   2499
26          16          7          ms sxcel   1599
27          12         10           pyspark   2499
28          12          1            python   2499
29          14          9            plotly    699
30           7          7          ms sxcel   1599
31           7          2               sql   3499
32          16          3     data analysis   4999
33          17         10           pyspark   2499
34          11          8            pandas   1099
35          14          6          power bi   1899
36          12          5           tableau   2499
37          12          7          ms sxcel   1599
38          18          8            pandas   1099
39           1         10           pyspark   2499
40           1          9            plotly    699
41           2          5           tableau   2499
42           7          6          power bi   1899
43          22          5           tableau   2499
44          22          6          power bi   1899
45          23          9            plotly    699
46          23          5           tableau   2499
47          14          4  machine learning   9999
48          14          1            python   2499
49          11         10           pyspark   2499
50          42          9            plotly    699
51          50          8            pandas   1099
52          38          1            python   2499

**Q5. Har student ne total kitne courses liye aue total kitna spend kiya, ye nikalo.**

**Answer:**

In [23]:
student_summary=final.groupby(
    ["student_id"]
).agg(
total_courses=("course_id","count"),
total_spent=("price","sum")
).sort_values("total_courses",ascending=False)
student_summary

            total_courses  total_spent
student_id
23                      6        22594
7                       5        10595
1                       4         7596
12                      4         9096
16                      4         9796
14                      4        15096
22                      3         9397
11                      3         5197
18                      3         5497
25                      2         4998
3                       2         7498
17                      2         4098
15                      2         4998
19                      2        13498
2                       1         2499
13                      1         4999
21                      1         2499
24                      1         9999
38                      1         2499
42                      1          699
50                      1         1099

**Q6. Sabse zyada courses lene wale student ki complete information nikalo.**

**Answer:**

In [24]:
top_student=student_summary.loc[
    student_summary["total_courses"].idxmax()
    ]
top_student

total_courses        6
total_spent      22594
Name: 23, dtype: int64

**Q7. Aise students ko filter karo jinhone kam se kam 2 courses liye hain.**

**Answer:**

In [36]:
student_summary

            total_courses  total_spent
student_id
23                      6        22594
7                       5        10595
1                       4         7596
12                      4         9096
16                      4         9796
14                      4        15096
22                      3         9397
11                      3         5197
18                      3         5497
25                      2         4998
3                       2         7498
17                      2         4098
15                      2         4998
19                      2        13498
2                       1         2499
13                      1         4999
21                      1         2499
24                      1         9999
38                      1         2499
42                      1          699
50                      1         1099

In [37]:
active_students=student_summary[student_summary['total_courses']>=2]
   
active_students

            total_courses  total_spent
student_id
23                      6        22594
7                       5        10595
1                       4         7596
12                      4         9096
16                      4         9796
14                      4        15096
22                      3         9397
11                      3         5197
18                      3         5497
25                      2         4998
3                       2         7498
17                      2         4098
15                      2         4998
19                      2        13498