# Pandas Merge - Program 3

In [1]:
import pandas as pd

In [ ]:
students=pd.read_csv("students.csv.xls")

In [3]:
month1=pd.read_csv("reg-month1.csv.xls")

In [4]:
month2=pd.read_csv("reg-month2.csv.xls")

In [5]:
courses=pd.read_csv("courses.csv.xls")

**Q1.Month 1 aur Month 2 regisraton data ko merge karke ek complete registration table bnao.**

**Answer:**

In [6]:
registrations=pd.concat(
    [
        month1.assign(month="Month 1"),
        month2.assign(month="Month 2")
   ],
    ignore_index=True
  )  
data=pd.merge(
        registrations,
        students,
        on="student_id",
        how="left"
    )
data=pd.merge(
       data,
       courses,
       on="course_id",
       how="left"
   )
data

,student_id,course_id,month,name,partner,course_name,price
0,23,1,Month 1,Chhavi Lachman,18.0,python,2499
1,15,5,Month 1,Preet Sha,16.0,tableau,2499
2,18,6,Month 1,Fardeen Mahabir,13.0,power bi,1899
3,23,4,Month 1,Chhavi Lachman,18.0,machine learning,9999
4,16,9,Month 1,Elias Dodiya,25.0,plotly,699
5,18,1,Month 1,Fardeen Mahabir,13.0,python,2499
6,1,1,Month 1,Kailash Harjo,23.0,python,2499
7,7,8,Month 1,Tarun Thaker,9.0,pandas,1099
8,22,3,Month 1,Yash Sethi,21.0,data analysis,4999
9,15,1,Month 1,Preet Sha,16.0,python,2499
10,19,4,Month 1,Qabeel Raman,12.0,machine learning,9999
11,1,6,Month 1,Kailash Harjo,23.0,power bi,1899
12,7,10,Month 1,Tarun Thaker,9.0,pyspark,2499
13,11,7,Month 1,David Mukhopadhyay,20.0,ms sxcel,1599
14,13,3,Month 1,Munni Varghese,24.0,data analysis,4999
15,24,4,Month 1,Radhika Suri,17.0,machine learning,9999
16,21,1,Month 1,Seema Kota,15.0,python,2499
17,16,5,Month 1,Elias Dodiya,25.0,tableau,2499
18,23,3,Month 1,Chhavi Lachman,18.0,data analysis,4999
19,17,7,Month 1,Yasmin Palan,7.0,ms sxcel,1599
20,23,6,Month 1,Chhavi Lachman,18.0,power bi,1899
21,25,1,Month 1,Shashank D’Alia,2.0,python,2499
22,19,2,Month 1,Qabeel Raman,12.0,sql,3499
23,25,10,Month 1,Shashank D’Alia,2.0,pyspark,2499
24,3,3,Month 1,Parveen Bhalla,3.0,data analysis,4999
25,3,5,Month 2,Parveen Bhalla,3.0,tableau,2499
26,16,7,Month 2,Elias Dodiya,25.0,ms sxcel,1599
27,12,10,Month 2,Radha Dutt,19.0,pyspark,2499
28,12,1,Month 2,Radha Dutt,19.0,python,2499
29,14,9,Month 2,Pranab Natarajan,22.0,plotly,699
30,7,7,Month 2,Tarun Thaker,9.0,ms sxcel,1599
31,7,2,Month 2,Tarun Thaker,9.0,sql,3499
32,16,3,Month 2,Elias Dodiya,25.0,data analysis,4999
33,17,10,Month 2,Yasmin Palan,7.0,pyspark,2499
34,11,8,Month 2,David Mukhopadhyay,20.0,pandas,1099
35,14,6,Month 2,Pranab Natarajan,22.0,power bi,1899
36,12,5,Month 2,Radha Dutt,19.0,tableau,2499
37,12,7,Month 2,Radha Dutt,19.0,ms sxcel,1599
38,18,8,Month 2,Fardeen Mahabir,13.0,pandas,1099
39,1,10,Month 2,Kailash Harjo,23.0,pyspark,2499
40,1,9,Month 2,Kailash Harjo,23.0,plotly,699
41,2,5,Month 2,Esha Butala,1.0,tableau,2499
42,7,6,Month 2,Tarun Thaker,9.0,power bi,1899
43,22,5,Month 2,Yash Sethi,21.0,tableau,2499
44,22,6,Month 2,Yash Sethi,21.0,power bi,1899
45,23,9,Month 2,Chhavi Lachman,18.0,plotly,699
46,23,5,Month 2,Chhavi Lachman,18.0,tableau,2499
47,14,4,Month 2,Pranab Natarajan,22.0,machine learning,9999
48,14,1,Month 2,Pranab Natarajan,22.0,python,2499
49,11,10,Month 2,David Mukhopadhyay,20.0,pyspark,2499
50,42,9,Month 2,NaN,NaN,plotly,699
51,50,8,Month 2,NaN,NaN,pandas,1099
52,38,1,Month 2,NaN,NaN,python,2499

**Q2. Har registration ke saath student ka naam,course name aur course price dikhao.**

**Answer:**

In [7]:
data[
    [
        "student_id",
        "name",
        "course_name",
        "price",
        "month"
    ]
]

    student_id                name       course_name  price    month
0           23      Chhavi Lachman            python   2499  Month 1
1           15           Preet Sha           tableau   2499  Month 1
2           18     Fardeen Mahabir          power bi   1899  Month 1
3           23      Chhavi Lachman  machine learning   9999  Month 1
4           16        Elias Dodiya            plotly    699  Month 1
5           18     Fardeen Mahabir            python   2499  Month 1
6            1       Kailash Harjo            python   2499  Month 1
7            7        Tarun Thaker            pandas   1099  Month 1
8           22          Yash Sethi     data analysis   4999  Month 1
9           15           Preet Sha            python   2499  Month 1
10          19        Qabeel Raman  machine learning   9999  Month 1
11           1       Kailash Harjo          power bi   1899  Month 1
12           7        Tarun Thaker           pyspark   2499  Month 1
13          11  David Mukhopadhyay          ms sxcel   1599  Month 1
14          13      Munni Varghese     data analysis   4999  Month 1
15          24        Radhika Suri  machine learning   9999  Month 1
16          21          Seema Kota            python   2499  Month 1
17          16        Elias Dodiya           tableau   2499  Month 1
18          23      Chhavi Lachman     data analysis   4999  Month 1
19          17        Yasmin Palan          ms sxcel   1599  Month 1
20          23      Chhavi Lachman          power bi   1899  Month 1
21          25     Shashank D’Alia            python   2499  Month 1
22          19        Qabeel Raman               sql   3499  Month 1
23          25     Shashank D’Alia           pyspark   2499  Month 1
24           3      Parveen Bhalla     data analysis   4999  Month 1
25           3      Parveen Bhalla           tableau   2499  Month 2
26          16        Elias Dodiya          ms sxcel   1599  Month 2
27          12          Radha Dutt           pyspark   2499  Month 2
28          12          Radha Dutt            python   2499  Month 2
29          14    Pranab Natarajan            plotly    699  Month 2
30           7        Tarun Thaker          ms sxcel   1599  Month 2
31           7        Tarun Thaker               sql   3499  Month 2
32          16        Elias Dodiya     data analysis   4999  Month 2
33          17        Yasmin Palan           pyspark   2499  Month 2
34          11  David Mukhopadhyay            pandas   1099  Month 2
35          14    Pranab Natarajan          power bi   1899  Month 2
36          12          Radha Dutt           tableau   2499  Month 2
37          12          Radha Dutt          ms sxcel   1599  Month 2
38          18     Fardeen Mahabir            pandas   1099  Month 2
39           1       Kailash Harjo           pyspark   2499  Month 2
40           1       Kailash Harjo            plotly    699  Month 2
41           2         Esha Butala           tableau   2499  Month 2
42           7        Tarun Thaker          power bi   1899  Month 2
43          22          Yash Sethi           tableau   2499  Month 2
44          22          Yash Sethi          power bi   1899  Month 2
45          23      Chhavi Lachman            plotly    699  Month 2
46          23      Chhavi Lachman           tableau   2499  Month 2
47          14    Pranab Natarajan  machine learning   9999  Month 2
48          14    Pranab Natarajan            python   2499  Month 2
49          11  David Mukhopadhyay           pyspark   2499  Month 2
50          42                 NaN            plotly    699  Month 2
51          50                 NaN            pandas   1099  Month 2
52          38                 NaN            python   2499  Month 2

**Q3. Har course ke liye Month 1 aur Month 2 ki registrations count karo.**

**Answer:**

In [17]:
course_month=data.groupby(
    ["course_name","month"]
).size().reset_index(name="registration")
course_month

         course_name    month  registration
0      data analysis  Month 1             4
1      data analysis  Month 2             1
2   machine learning  Month 1             3
3   machine learning  Month 2             1
4           ms sxcel  Month 1             2
5           ms sxcel  Month 2             3
6             pandas  Month 1             1
7             pandas  Month 2             3
8             plotly  Month 1             1
9             plotly  Month 2             4
10          power bi  Month 1             3
11          power bi  Month 2             3
12           pyspark  Month 1             2
13           pyspark  Month 2             4
14            python  Month 1             6
15            python  Month 2             3
16               sql  Month 1             1
17               sql  Month 2             1
18           tableau  Month 1             2
19           tableau  Month 2             5

**Q4. har course ki total registrations, unique students aur total revenue nikalo.**

**Answer:**

In [9]:
course_summary=data.groupby("course_name").agg(
    total_registrations=("student_id","count"),
    unique_students=("student_id","nunique"),
    total_revenue=("price","sum")
).sort_values(
    "total_registrations",
    ascending=False
)
course_summary

                  total_registrations  unique_students  total_revenue
course_name
python                              9                9          22491
tableau                             7                7          17493
power bi                            6                6          11394
pyspark                             6                6          14994
ms sxcel                            5                5           7995
data analysis                       5                5          24995
plotly                              5                5           3495
machine learning                    4                4          39996
pandas                              4                4           4396
sql                                 2                2           6998

**Q5.Har registration ke sath us course ki total registration count add karo.**

**Answer:**

In [10]:
data["course_total_registrations"]=data.groupby(
    "course_id"
)["student_id"].transform("count")
print(
data[
    [
        "student_id",
        "name",
        "course_name",
        "month",
        "course_total_registrations"
    ]
 ]
)
data

    student_id                name       course_name    month  \
0           23      Chhavi Lachman            python  Month 1
1           15           Preet Sha           tableau  Month 1
2           18     Fardeen Mahabir          power bi  Month 1
3           23      Chhavi Lachman  machine learning  Month 1
4           16        Elias Dodiya            plotly  Month 1
5           18     Fardeen Mahabir            python  Month 1
6            1       Kailash Harjo            python  Month 1
7            7        Tarun Thaker            pandas  Month 1
8           22          Yash Sethi     data analysis  Month 1
9           15           Preet Sha            python  Month 1
10          19        Qabeel Raman  machine learning  Month 1
11           1       Kailash Harjo          power bi  Month 1
12           7        Tarun Thaker           pyspark  Month 1
13          11  David Mukhopadhyay          ms sxcel  Month 1
14          13      Munni Varghese     data analysis  Month 1
15          24        Radhika Suri  machine learning  Month 1
16          21          Seema Kota            python  Month 1
17          16        Elias Dodiya           tableau  Month 1
18          23      Chhavi Lachman     data analysis  Month 1
19          17        Yasmin Palan          ms sxcel  Month 1
20          23      Chhavi Lachman          power bi  Month 1
21          25     Shashank D’Alia            python  Month 1
22          19        Qabeel Raman               sql  Month 1
23          25     Shashank D’Alia           pyspark  Month 1
24           3      Parveen Bhalla     data analysis  Month 1
25           3      Parveen Bhalla           tableau  Month 2
26          16        Elias Dodiya          ms sxcel  Month 2
27          12          Radha Dutt           pyspark  Month 2
28          12          Radha Dutt            python  Month 2
29          14    Pranab Natarajan            plotly  Month 2
30           7        Tarun Thaker          ms sxcel  Month 2
31           7        Tarun Thaker               sql  Month 2
32          16        Elias Dodiya     data analysis  Month 2
33          17        Yasmin Palan           pyspark  Month 2
34          11  David Mukhopadhyay            pandas  Month 2
35          14    Pranab Natarajan          power bi  Month 2
36          12          Radha Dutt           tableau  Month 2
37          12          Radha Dutt          ms sxcel  Month 2
38          18     Fardeen Mahabir            pandas  Month 2
39           1       Kailash Harjo           pyspark  Month 2
40           1       Kailash Harjo            plotly  Month 2
41           2         Esha Butala           tableau  Month 2
42           7        Tarun Thaker          power bi  Month 2
43          22          Yash Sethi           tableau  Month 2
44          22          Yash Sethi          power bi  Month 2
45          23      Chhavi Lachman            plotly  Month 2
46          23      Chhavi Lachman           tableau  Month 2
47          14    Pranab Natarajan  machine learning  Month 2
48          14    Pranab Natarajan            python  Month 2
49          11  David Mukhopadhyay           pyspark  Month 2
50          42                 NaN            plotly  Month 2
51          50                 NaN            pandas  Month 2
52          38                 NaN            python  Month 2

    course_total_registrations
0                            9
1                            7
2                            6
3                            4
4                            5
5                            9
6                            9
7                            4
8                            5
9                            9
10                           4
11                           6
12                           6
13                           5
14                           5
15                           4
16                           9
17                           7
18                           5
19                           5
20                           6
21                           9
22                           2
23                           6
24                           5
25                           7
26                           5
27                           6
28                           9
29                           5
30                           5
31                           2
32                           5
33                           6
34                           4
35                           6
36                           7
37                           5
38                           4
39                           6
40                           5
41                           7
42                           6
43                           7
44                           6
45                           5
46                           7
47                           4
48                           9
49                           6
50                           5
51                           4
52                           9

,student_id,course_id,month,name,partner,course_name,price,course_total_registrations
0,23,1,Month 1,Chhavi Lachman,18.0,python,2499,9
1,15,5,Month 1,Preet Sha,16.0,tableau,2499,7
2,18,6,Month 1,Fardeen Mahabir,13.0,power bi,1899,6
3,23,4,Month 1,Chhavi Lachman,18.0,machine learning,9999,4
4,16,9,Month 1,Elias Dodiya,25.0,plotly,699,5
5,18,1,Month 1,Fardeen Mahabir,13.0,python,2499,9
6,1,1,Month 1,Kailash Harjo,23.0,python,2499,9
7,7,8,Month 1,Tarun Thaker,9.0,pandas,1099,4
8,22,3,Month 1,Yash Sethi,21.0,data analysis,4999,5
9,15,1,Month 1,Preet Sha,16.0,python,2499,9
10,19,4,Month 1,Qabeel Raman,12.0,machine learning,9999,4
11,1,6,Month 1,Kailash Harjo,23.0,power bi,1899,6
12,7,10,Month 1,Tarun Thaker,9.0,pyspark,2499,6
13,11,7,Month 1,David Mukhopadhyay,20.0,ms sxcel,1599,5
14,13,3,Month 1,Munni Varghese,24.0,data analysis,4999,5
15,24,4,Month 1,Radhika Suri,17.0,machine learning,9999,4
16,21,1,Month 1,Seema Kota,15.0,python,2499,9
17,16,5,Month 1,Elias Dodiya,25.0,tableau,2499,7
18,23,3,Month 1,Chhavi Lachman,18.0,data analysis,4999,5
19,17,7,Month 1,Yasmin Palan,7.0,ms sxcel,1599,5
20,23,6,Month 1,Chhavi Lachman,18.0,power bi,1899,6
21,25,1,Month 1,Shashank D’Alia,2.0,python,2499,9
22,19,2,Month 1,Qabeel Raman,12.0,sql,3499,2
23,25,10,Month 1,Shashank D’Alia,2.0,pyspark,2499,6
24,3,3,Month 1,Parveen Bhalla,3.0,data analysis,4999,5
25,3,5,Month 2,Parveen Bhalla,3.0,tableau,2499,7
26,16,7,Month 2,Elias Dodiya,25.0,ms sxcel,1599,5
27,12,10,Month 2,Radha Dutt,19.0,pyspark,2499,6
28,12,1,Month 2,Radha Dutt,19.0,python,2499,9
29,14,9,Month 2,Pranab Natarajan,22.0,plotly,699,5
30,7,7,Month 2,Tarun Thaker,9.0,ms sxcel,1599,5
31,7,2,Month 2,Tarun Thaker,9.0,sql,3499,2
32,16,3,Month 2,Elias Dodiya,25.0,data analysis,4999,5
33,17,10,Month 2,Yasmin Palan,7.0,pyspark,2499,6
34,11,8,Month 2,David Mukhopadhyay,20.0,pandas,1099,4
35,14,6,Month 2,Pranab Natarajan,22.0,power bi,1899,6
36,12,5,Month 2,Radha Dutt,19.0,tableau,2499,7
37,12,7,Month 2,Radha Dutt,19.0,ms sxcel,1599,5
38,18,8,Month 2,Fardeen Mahabir,13.0,pandas,1099,4
39,1,10,Month 2,Kailash Harjo,23.0,pyspark,2499,6
40,1,9,Month 2,Kailash Harjo,23.0,plotly,699,5
41,2,5,Month 2,Esha Butala,1.0,tableau,2499,7
42,7,6,Month 2,Tarun Thaker,9.0,power bi,1899,6
43,22,5,Month 2,Yash Sethi,21.0,tableau,2499,7
44,22,6,Month 2,Yash Sethi,21.0,power bi,1899,6
45,23,9,Month 2,Chhavi Lachman,18.0,plotly,699,5
46,23,5,Month 2,Chhavi Lachman,18.0,tableau,2499,7
47,14,4,Month 2,Pranab Natarajan,22.0,machine learning,9999,4
48,14,1,Month 2,Pranab Natarajan,22.0,python,2499,9
49,11,10,Month 2,David Mukhopadhyay,20.0,pyspark,2499,6
50,42,9,Month 2,NaN,NaN,plotly,699,5
51,50,8,Month 2,NaN,NaN,pandas,1099,4
52,38,1,Month 2,NaN,NaN,python,2499,9

**Q.6 sabse jada revenue genrerate karne wale course ki complete summary nikalo.**

**Answer:**

In [11]:
best_course=course_summary.loc[
    course_summary["total_revenue"].idxmax()
    ]
best_course

total_registrations        4
unique_students            4
total_revenue          39996
Name: machine learning, dtype: int64

**Q.7 course price ke basis par expensive coursesselect kro jinke price 3000 se zyada hai.**

**Answer:**

In [12]:
expensive_course=data[
    data["price"]>3000
    ][
    [
        "student_id",
        "name",
        "course_name",
        "price",
        "month"
    ]
 ]
expensive_course

    student_id              name       course_name  price    month
3           23    Chhavi Lachman  machine learning   9999  Month 1
8           22        Yash Sethi     data analysis   4999  Month 1
10          19      Qabeel Raman  machine learning   9999  Month 1
14          13    Munni Varghese     data analysis   4999  Month 1
15          24      Radhika Suri  machine learning   9999  Month 1
18          23    Chhavi Lachman     data analysis   4999  Month 1
22          19      Qabeel Raman               sql   3499  Month 1
24           3    Parveen Bhalla     data analysis   4999  Month 1
31           7      Tarun Thaker               sql   3499  Month 2
32          16      Elias Dodiya     data analysis   4999  Month 2
47          14  Pranab Natarajan  machine learning   9999  Month 2

**Q8. students aue unke partners ke name ko merge karke partner information wali table banao.**

**Answer:**

In [20]:
students.head()

   student_id            name  partner
0           1   Kailash Harjo       23
1           2     Esha Butala        1
2           3  Parveen Bhalla        3
3           4     Marlo Dugal       14
4           5     Kusum Bahri        6

In [23]:
partner_data=pd.merge(
    students,
    students[["student_id","name"]], 
    left_on="partner",
    right_on="student_id",
    how="left",
  suffixes=("","_partner"))
partner_data

,student_id,name,partner,student_id_partner,name_partner
0,1,Kailash Harjo,23,23,Chhavi Lachman
1,2,Esha Butala,1,1,Kailash Harjo
2,3,Parveen Bhalla,3,3,Parveen Bhalla
3,4,Marlo Dugal,14,14,Pranab Natarajan
4,5,Kusum Bahri,6,6,Lakshmi Contractor
5,6,Lakshmi Contractor,10,10,Aayushman Sant
6,7,Tarun Thaker,9,9,Nitika Chatterjee
7,8,Radheshyam Dey,5,5,Kusum Bahri
8,9,Nitika Chatterjee,4,4,Marlo Dugal
9,10,Aayushman Sant,8,8,Radheshyam Dey
10,11,David Mukhopadhyay,20,20,Hanuman Hegde
11,12,Radha Dutt,19,19,Qabeel Raman
12,13,Munni Varghese,24,24,Radhika Suri
13,14,Pranab Natarajan,22,22,Yash Sethi
14,15,Preet Sha,16,16,Elias Dodiya
15,16,Elias Dodiya,25,25,Shashank D’Alia
16,17,Yasmin Palan,7,7,Tarun Thaker
17,18,Fardeen Mahabir,13,13,Munni Varghese
18,19,Qabeel Raman,12,12,Radha Dutt
19,20,Hanuman Hegde,11,11,David Mukhopadhyay
20,21,Seema Kota,15,15,Preet Sha
21,22,Yash Sethi,21,21,Seema Kota
22,23,Chhavi Lachman,18,18,Fardeen Mahabir
23,24,Radhika Suri,17,17,Yasmin Palan
24,25,Shashank D’Alia,2,2,Esha Butala

In [13]:
partner_data=pd.merge(
    students,
    students[["student_id","name"]],
    left_on="partner",
    right_on="student_id",
    how="left",
    suffixes=("","_partner")
)

partner_data[
    [
        "student_id",
        "name",
        "partner",
        "name_partner"
    ]
    ]

    student_id                name  partner        name_partner
0            1       Kailash Harjo       23      Chhavi Lachman
1            2         Esha Butala        1       Kailash Harjo
2            3      Parveen Bhalla        3      Parveen Bhalla
3            4         Marlo Dugal       14    Pranab Natarajan
4            5         Kusum Bahri        6  Lakshmi Contractor
5            6  Lakshmi Contractor       10      Aayushman Sant
6            7        Tarun Thaker        9   Nitika Chatterjee
7            8      Radheshyam Dey        5         Kusum Bahri
8            9   Nitika Chatterjee        4         Marlo Dugal
9           10      Aayushman Sant        8      Radheshyam Dey
10          11  David Mukhopadhyay       20       Hanuman Hegde
11          12          Radha Dutt       19        Qabeel Raman
12          13      Munni Varghese       24        Radhika Suri
13          14    Pranab Natarajan       22          Yash Sethi
14          15           Preet Sha       16        Elias Dodiya
15          16        Elias Dodiya       25     Shashank D’Alia
16          17        Yasmin Palan        7        Tarun Thaker
17          18     Fardeen Mahabir       13      Munni Varghese
18          19        Qabeel Raman       12          Radha Dutt
19          20       Hanuman Hegde       11  David Mukhopadhyay
20          21          Seema Kota       15           Preet Sha
21          22          Yash Sethi       21          Seema Kota
22          23      Chhavi Lachman       18     Fardeen Mahabir
23          24        Radhika Suri       17        Yasmin Palan
24          25     Shashank D’Alia        2         Esha Butala