# Pandas Merge - program 4(New Questions)

In [1]:
import pandas as pd

In [2]:
students=pd.read_csv("students.csv.xls")

In [3]:
month1=pd.read_csv("reg-month1.csv.xls")

In [4]:
month2=pd.read_csv("reg-month2.csv.xls")

In [5]:
courses=pd.read_csv("courses.csv.xls")

**Q1. Students dataset me student_id aur name kouse karke student_info banao aur Month 1 registrations ke sath.**

**Answer:**

In [6]:
student_info=students[["student_id","name"]]
result1=pd.merge(month1,student_info,
                 on="student_id",
                 how="left")
result1

    student_id  course_id                name
0           23          1      Chhavi Lachman
1           15          5           Preet Sha
2           18          6     Fardeen Mahabir
3           23          4      Chhavi Lachman
4           16          9        Elias Dodiya
5           18          1     Fardeen Mahabir
6            1          1       Kailash Harjo
7            7          8        Tarun Thaker
8           22          3          Yash Sethi
9           15          1           Preet Sha
10          19          4        Qabeel Raman
11           1          6       Kailash Harjo
12           7         10        Tarun Thaker
13          11          7  David Mukhopadhyay
14          13          3      Munni Varghese
15          24          4        Radhika Suri
16          21          1          Seema Kota
17          16          5        Elias Dodiya
18          23          3      Chhavi Lachman
19          17          7        Yasmin Palan
20          23          6      Chhavi Lachman
21          25          1     Shashank D’Alia
22          19          2        Qabeel Raman
23          25         10     Shashank D’Alia
24           3          3      Parveen Bhalla

**Q2. Course dataset se sirf course_id aur course_namelaker Month2 registration ke saath merge karo.**

**Answer:**

In [7]:
course_info=courses[["course_id","course_name"]]
result2=pd.merge(month2, course_info,on="course_id",how="left")
result2

    student_id  course_id       course_name
0            3          5           tableau
1           16          7          ms sxcel
2           12         10           pyspark
3           12          1            python
4           14          9            plotly
5            7          7          ms sxcel
6            7          2               sql
7           16          3     data analysis
8           17         10           pyspark
9           11          8            pandas
10          14          6          power bi
11          12          5           tableau
12          12          7          ms sxcel
13          18          8            pandas
14           1         10           pyspark
15           1          9            plotly
16           2          5           tableau
17           7          6          power bi
18          22          5           tableau
19          22          6          power bi
20          23          9            plotly
21          23          5           tableau
22          14          4  machine learning
23          14          1            python
24          11         10           pyspark
25          42          9            plotly
26          50          8            pandas
27          38          1            python

**Q3. Month1 registrations me students aur courses dono ki information merge karke final table banao.**

**Answer:**

In [8]:
result3=month1.merge(
    students[["student_id","name"]],
              on="student_id",
              how="left"
).merge(
    courses[["course_id","course_name","price"]],
             on="course_id",
             how="left"
)
result3

    student_id  course_id                name       course_name  price
0           23          1      Chhavi Lachman            python   2499
1           15          5           Preet Sha           tableau   2499
2           18          6     Fardeen Mahabir          power bi   1899
3           23          4      Chhavi Lachman  machine learning   9999
4           16          9        Elias Dodiya            plotly    699
5           18          1     Fardeen Mahabir            python   2499
6            1          1       Kailash Harjo            python   2499
7            7          8        Tarun Thaker            pandas   1099
8           22          3          Yash Sethi     data analysis   4999
9           15          1           Preet Sha            python   2499
10          19          4        Qabeel Raman  machine learning   9999
11           1          6       Kailash Harjo          power bi   1899
12           7         10        Tarun Thaker           pyspark   2499
13          11          7  David Mukhopadhyay          ms sxcel   1599
14          13          3      Munni Varghese     data analysis   4999
15          24          4        Radhika Suri  machine learning   9999
16          21          1          Seema Kota            python   2499
17          16          5        Elias Dodiya           tableau   2499
18          23          3      Chhavi Lachman     data analysis   4999
19          17          7        Yasmin Palan          ms sxcel   1599
20          23          6      Chhavi Lachman          power bi   1899
21          25          1     Shashank D’Alia            python   2499
22          19          2        Qabeel Raman               sql   3499
23          25         10     Shashank D’Alia           pyspark   2499
24           3          3      Parveen Bhalla     data analysis   4999

In [9]:
result3[["student_id","name","course_id","course_name","price"]]

    student_id                name  course_id       course_name  price
0           23      Chhavi Lachman          1            python   2499
1           15           Preet Sha          5           tableau   2499
2           18     Fardeen Mahabir          6          power bi   1899
3           23      Chhavi Lachman          4  machine learning   9999
4           16        Elias Dodiya          9            plotly    699
5           18     Fardeen Mahabir          1            python   2499
6            1       Kailash Harjo          1            python   2499
7            7        Tarun Thaker          8            pandas   1099
8           22          Yash Sethi          3     data analysis   4999
9           15           Preet Sha          1            python   2499
10          19        Qabeel Raman          4  machine learning   9999
11           1       Kailash Harjo          6          power bi   1899
12           7        Tarun Thaker         10           pyspark   2499
13          11  David Mukhopadhyay          7          ms sxcel   1599
14          13      Munni Varghese          3     data analysis   4999
15          24        Radhika Suri          4  machine learning   9999
16          21          Seema Kota          1            python   2499
17          16        Elias Dodiya          5           tableau   2499
18          23      Chhavi Lachman          3     data analysis   4999
19          17        Yasmin Palan          7          ms sxcel   1599
20          23      Chhavi Lachman          6          power bi   1899
21          25     Shashank D’Alia          1            python   2499
22          19        Qabeel Raman          2               sql   3499
23          25     Shashank D’Alia         10           pyspark   2499
24           3      Parveen Bhalla          3     data analysis   4999

In [10]:
month1

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [11]:
month2

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [12]:
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

**Q4. Month 1 aur Month 2 registrations ko students ke naam ke sath merge karke ek dataFrameme combine karo.**

**Answer:**

In [25]:
month1_named=month1.merge(
    students,
    on="student_id",
    how="left"
)
month2_named=month2.merge(
    students,
    on="student_id",
    how="left"
)
dataframe = pd.concat([month1_named,month2_named],ignore_index=True)
dataframe

    student_id  course_id                name  partner
0           23          1      Chhavi Lachman     18.0
1           15          5           Preet Sha     16.0
2           18          6     Fardeen Mahabir     13.0
3           23          4      Chhavi Lachman     18.0
4           16          9        Elias Dodiya     25.0
5           18          1     Fardeen Mahabir     13.0
6            1          1       Kailash Harjo     23.0
7            7          8        Tarun Thaker      9.0
8           22          3          Yash Sethi     21.0
9           15          1           Preet Sha     16.0
10          19          4        Qabeel Raman     12.0
11           1          6       Kailash Harjo     23.0
12           7         10        Tarun Thaker      9.0
13          11          7  David Mukhopadhyay     20.0
14          13          3      Munni Varghese     24.0
15          24          4        Radhika Suri     17.0
16          21          1          Seema Kota     15.0
17          16          5        Elias Dodiya     25.0
18          23          3      Chhavi Lachman     18.0
19          17          7        Yasmin Palan      7.0
20          23          6      Chhavi Lachman     18.0
21          25          1     Shashank D’Alia      2.0
22          19          2        Qabeel Raman     12.0
23          25         10     Shashank D’Alia      2.0
24           3          3      Parveen Bhalla      3.0
25           3          5      Parveen Bhalla      3.0
26          16          7        Elias Dodiya     25.0
27          12         10          Radha Dutt     19.0
28          12          1          Radha Dutt     19.0
29          14          9    Pranab Natarajan     22.0
30           7          7        Tarun Thaker      9.0
31           7          2        Tarun Thaker      9.0
32          16          3        Elias Dodiya     25.0
33          17         10        Yasmin Palan      7.0
34          11          8  David Mukhopadhyay     20.0
35          14          6    Pranab Natarajan     22.0
36          12          5          Radha Dutt     19.0
37          12          7          Radha Dutt     19.0
38          18          8     Fardeen Mahabir     13.0
39           1         10       Kailash Harjo     23.0
40           1          9       Kailash Harjo     23.0
41           2          5         Esha Butala      1.0
42           7          6        Tarun Thaker      9.0
43          22          5          Yash Sethi     21.0
44          22          6          Yash Sethi     21.0
45          23          9      Chhavi Lachman     18.0
46          23          5      Chhavi Lachman     18.0
47          14          4    Pranab Natarajan     22.0
48          14          1    Pranab Natarajan     22.0
49          11         10  David Mukhopadhyay     20.0
50          42          9                 NaN      NaN
51          50          8                 NaN      NaN
52          38          1                 NaN      NaN

**Q5. Student dataset ko khud ke sath partner column ke through merge karke student aur partner dono ke name.**

**Answer:**

In [26]:
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

In [15]:
student_partner=pd.merge(
    students,
    students[["student_id","name"]],
    left_on="partner",
    right_on="student_id",
    how="left",
    suffixes=("_student","_partner")
)
student_partner[["student_id_student","name_student","partner","name_partner"]]

    student_id_student        name_student  partner        name_partner
0                    1       Kailash Harjo       23      Chhavi Lachman
1                    2         Esha Butala        1       Kailash Harjo
2                    3      Parveen Bhalla        3      Parveen Bhalla
3                    4         Marlo Dugal       14    Pranab Natarajan
4                    5         Kusum Bahri        6  Lakshmi Contractor
5                    6  Lakshmi Contractor       10      Aayushman Sant
6                    7        Tarun Thaker        9   Nitika Chatterjee
7                    8      Radheshyam Dey        5         Kusum Bahri
8                    9   Nitika Chatterjee        4         Marlo Dugal
9                   10      Aayushman Sant        8      Radheshyam Dey
10                  11  David Mukhopadhyay       20       Hanuman Hegde
11                  12          Radha Dutt       19        Qabeel Raman
12                  13      Munni Varghese       24        Radhika Suri
13                  14    Pranab Natarajan       22          Yash Sethi
14                  15           Preet Sha       16        Elias Dodiya
15                  16        Elias Dodiya       25     Shashank D’Alia
16                  17        Yasmin Palan        7        Tarun Thaker
17                  18     Fardeen Mahabir       13      Munni Varghese
18                  19        Qabeel Raman       12          Radha Dutt
19                  20       Hanuman Hegde       11  David Mukhopadhyay
20                  21          Seema Kota       15           Preet Sha
21                  22          Yash Sethi       21          Seema Kota
22                  23      Chhavi Lachman       18     Fardeen Mahabir
23                  24        Radhika Suri       17        Yasmin Palan
24                  25     Shashank D’Alia        2         Esha Butala

**Q6.month1 registrations ko courses ke aath merge karke price aur course ki averge price compare karo.**

**Answer:**

In [31]:
month1

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [29]:
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [30]:
price_data=month1.merge(
    courses[["course_id","course_name","price"]],
    on="course_id",
    how="left"
)
price_data

    student_id  course_id       course_name  price
0           23          1            python   2499
1           15          5           tableau   2499
2           18          6          power bi   1899
3           23          4  machine learning   9999
4           16          9            plotly    699
5           18          1            python   2499
6            1          1            python   2499
7            7          8            pandas   1099
8           22          3     data analysis   4999
9           15          1            python   2499
10          19          4  machine learning   9999
11           1          6          power bi   1899
12           7         10           pyspark   2499
13          11          7          ms sxcel   1599
14          13          3     data analysis   4999
15          24          4  machine learning   9999
16          21          1            python   2499
17          16          5           tableau   2499
18          23          3     data analysis   4999
19          17          7          ms sxcel   1599
20          23          6          power bi   1899
21          25          1            python   2499
22          19          2               sql   3499
23          25         10           pyspark   2499
24           3          3     data analysis   4999

In [32]:
price_data["course_average_price"]=price_data.groupby(
    "course_id"
)["price"].transform("mean")

price_data

    student_id  course_id       course_name  price  course_average_price
0           23          1            python   2499                2499.0
1           15          5           tableau   2499                2499.0
2           18          6          power bi   1899                1899.0
3           23          4  machine learning   9999                9999.0
4           16          9            plotly    699                 699.0
5           18          1            python   2499                2499.0
6            1          1            python   2499                2499.0
7            7          8            pandas   1099                1099.0
8           22          3     data analysis   4999                4999.0
9           15          1            python   2499                2499.0
10          19          4  machine learning   9999                9999.0
11           1          6          power bi   1899                1899.0
12           7         10           pyspark   2499                2499.0
13          11          7          ms sxcel   1599                1599.0
14          13          3     data analysis   4999                4999.0
15          24          4  machine learning   9999                9999.0
16          21          1            python   2499                2499.0
17          16          5           tableau   2499                2499.0
18          23          3     data analysis   4999                4999.0
19          17          7          ms sxcel   1599                1599.0
20          23          6          power bi   1899                1899.0
21          25          1            python   2499                2499.0
22          19          2               sql   3499                3499.0
23          25         10           pyspark   2499                2499.0
24           3          3     data analysis   4999                4999.0

In [33]:
price_data["price_difference"]=(price_data["price"]-price_data["course_average_price"])
price_data[[
"course_id","course_name","price",
"course_average_price","price_difference"
]]
price_data

,student_id,course_id,course_name,price,course_average_price,price_difference
0,23,1,python,2499,2499.0,0.0
1,15,5,tableau,2499,2499.0,0.0
2,18,6,power bi,1899,1899.0,0.0
3,23,4,machine learning,9999,9999.0,0.0
4,16,9,plotly,699,699.0,0.0
5,18,1,python,2499,2499.0,0.0
6,1,1,python,2499,2499.0,0.0
7,7,8,pandas,1099,1099.0,0.0
8,22,3,data analysis,4999,4999.0,0.0
9,15,1,python,2499,2499.0,0.0
10,19,4,machine learning,9999,9999.0,0.0
11,1,6,power bi,1899,1899.0,0.0
12,7,10,pyspark,2499,2499.0,0.0
13,11,7,ms sxcel,1599,1599.0,0.0
14,13,3,data analysis,4999,4999.0,0.0
15,24,4,machine learning,9999,9999.0,0.0
16,21,1,python,2499,2499.0,0.0
17,16,5,tableau,2499,2499.0,0.0
18,23,3,data analysis,4999,4999.0,0.0
19,17,7,ms sxcel,1599,1599.0,0.0
20,23,6,power bi,1899,1899.0,0.0
21,25,1,python,2499,2499.0,0.0
22,19,2,sql,3499,3499.0,0.0
23,25,10,pyspark,2499,2499.0,0.0
24,3,3,data analysis,4999,4999.0,0.0

**Q7. Month 1 aur month 2 ke course registrations ko course_id ke basis par compare karo.**

**Answer:**

In [34]:
month1

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [35]:
month2

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [43]:
m1_count=month1.groupby("course_id").size().reset_index(name="month1_count")
m2_count=month2.groupby("course_id").size().reset_index(name="month2_count")
print(m1_count)
print(m2_count)

   course_id  month1_count
0          1             6
1          2             1
2          3             4
3          4             3
4          5             2
5          6             3
6          7             2
7          8             1
8          9             1
9         10             2
   course_id  month2_count
0          1             3
1          2             1
2          3             1
3          4             1
4          5             5
5          6             3
6          7             3
7          8             3
8          9             4
9         10             4

In [46]:
comparison=pd.merge(
    m1_count,
    m2_count,
    on="course_id",
    how="outer"
).fillna(0)
comparison

   course_id  month1_count  month2_count
0          1             6             3
1          2             1             1
2          3             4             1
3          4             3             1
4          5             2             5
5          6             3             3
6          7             2             3
7          8             1             3
8          9             1             4
9         10             2             4

In [47]:
comparison=comparison.merge(
    courses[["course_id","course_name"]],
    on="course_id",
    how="left"
)
comparison

   course_id  month1_count  month2_count       course_name
0          1             6             3            python
1          2             1             1               sql
2          3             4             1     data analysis
3          4             3             1  machine learning
4          5             2             5           tableau
5          6             3             3          power bi
6          7             2             3          ms sxcel
7          8             1             3            pandas
8          9             1             4            plotly
9         10             2             4           pyspark

In [48]:
comparison["difference"]=(
   comparison["month2_count"]- comparison["month1_count"]
)
comparison

   course_id  month1_count  month2_count       course_name  difference
0          1             6             3            python          -3
1          2             1             1               sql           0
2          3             4             1     data analysis          -3
3          4             3             1  machine learning          -2
4          5             2             5           tableau           3
5          6             3             3          power bi           0
6          7             2             3          ms sxcel           1
7          8             1             3            pandas           2
8          9             1             4            plotly           3
9         10             2             4           pyspark           2

**Q8. un students ko nikalo jinki month2 registration month1 se jyada hai.**

**Answer:**

In [52]:
comparison

   course_id  month1_count  month2_count       course_name  difference
0          1             6             3            python          -3
1          2             1             1               sql           0
2          3             4             1     data analysis          -3
3          4             3             1  machine learning          -2
4          5             2             5           tableau           3
5          6             3             3          power bi           0
6          7             2             3          ms sxcel           1
7          8             1             3            pandas           2
8          9             1             4            plotly           3
9         10             2             4           pyspark           2

In [53]:
more_registrations=comparison[
    comparison["month2_count"]>comparison["month1_count"]
    ]
more_registrations

   course_id  month1_count  month2_count course_name  difference
4          5             2             5     tableau           3
6          7             2             3    ms sxcel           1
7          8             1             3      pandas           2
8          9             1             4      plotly           3
9         10             2             4     pyspark           2

**Q9. students aur courses ko merge karne ke baad course_wise unique students ki count nikalo.**

**Answer:**

In [56]:
students_courses=month1.merge(
    students[["student_id","name"]],
    on="student_id",
    how="left"
).merge(
    courses[["course_id","course_name"]],
    on="course_id",
how="left"
)
students_courses

    student_id  course_id                name       course_name
0           23          1      Chhavi Lachman            python
1           15          5           Preet Sha           tableau
2           18          6     Fardeen Mahabir          power bi
3           23          4      Chhavi Lachman  machine learning
4           16          9        Elias Dodiya            plotly
5           18          1     Fardeen Mahabir            python
6            1          1       Kailash Harjo            python
7            7          8        Tarun Thaker            pandas
8           22          3          Yash Sethi     data analysis
9           15          1           Preet Sha            python
10          19          4        Qabeel Raman  machine learning
11           1          6       Kailash Harjo          power bi
12           7         10        Tarun Thaker           pyspark
13          11          7  David Mukhopadhyay          ms sxcel
14          13          3      Munni Varghese     data analysis
15          24          4        Radhika Suri  machine learning
16          21          1          Seema Kota            python
17          16          5        Elias Dodiya           tableau
18          23          3      Chhavi Lachman     data analysis
19          17          7        Yasmin Palan          ms sxcel
20          23          6      Chhavi Lachman          power bi
21          25          1     Shashank D’Alia            python
22          19          2        Qabeel Raman               sql
23          25         10     Shashank D’Alia           pyspark
24           3          3      Parveen Bhalla     data analysis

In [54]:
unique_students=students_courses.groupby(
    "course_name"
)["student_id"].nunique().sort_values(ascending=False)
unique_students

course_name
python              6
data analysis       4
machine learning    3
power bi            3
pyspark             2
ms sxcel            2
tableau             2
pandas              1
plotly              1
sql                 1
Name: student_id, dtype: int64

**Q10. students aur courses ko merge karne ke bad har student ke courses ki list nikalo.**

**Answer:**

In [57]:
students_courses

    student_id  course_id                name       course_name
0           23          1      Chhavi Lachman            python
1           15          5           Preet Sha           tableau
2           18          6     Fardeen Mahabir          power bi
3           23          4      Chhavi Lachman  machine learning
4           16          9        Elias Dodiya            plotly
5           18          1     Fardeen Mahabir            python
6            1          1       Kailash Harjo            python
7            7          8        Tarun Thaker            pandas
8           22          3          Yash Sethi     data analysis
9           15          1           Preet Sha            python
10          19          4        Qabeel Raman  machine learning
11           1          6       Kailash Harjo          power bi
12           7         10        Tarun Thaker           pyspark
13          11          7  David Mukhopadhyay          ms sxcel
14          13          3      Munni Varghese     data analysis
15          24          4        Radhika Suri  machine learning
16          21          1          Seema Kota            python
17          16          5        Elias Dodiya           tableau
18          23          3      Chhavi Lachman     data analysis
19          17          7        Yasmin Palan          ms sxcel
20          23          6      Chhavi Lachman          power bi
21          25          1     Shashank D’Alia            python
22          19          2        Qabeel Raman               sql
23          25         10     Shashank D’Alia           pyspark
24           3          3      Parveen Bhalla     data analysis

In [58]:
student_course_list=students_courses.groupby(
    ["student_id","name"]
)[["course_name","course_id"]].agg(list).reset_index()
student_course_list

,student_id,name,course_name,course_id
0,1,Kailash Harjo,"[python, power bi]","[1, 6]"
1,3,Parveen Bhalla,[data analysis],[3]
2,7,Tarun Thaker,"[pandas, pyspark]","[8, 10]"
3,11,David Mukhopadhyay,[ms sxcel],[7]
4,13,Munni Varghese,[data analysis],[3]
5,15,Preet Sha,"[tableau, python]","[5, 1]"
6,16,Elias Dodiya,"[plotly, tableau]","[9, 5]"
7,17,Yasmin Palan,[ms sxcel],[7]
8,18,Fardeen Mahabir,"[power bi, python]","[6, 1]"
9,19,Qabeel Raman,"[machine learning, sql]","[4, 2]"
10,21,Seema Kota,[python],[1]
11,22,Yash Sethi,[data analysis],[3]
12,23,Chhavi Lachman,"[python, machine learning, data analysis, powe...","[1, 4, 3, 6]"
13,24,Radhika Suri,[machine learning],[4]
14,25,Shashank D’Alia,"[python, pyspark]","[1, 10]"