In [1]:
import pandas as pd

In [2]:
multiindex=pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [3]:
branch_df1=pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16]],
    index=multiindex,
    columns=['avg_package','student']
)
branch_df1

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ece 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [4]:
branch_df1.loc['cse',2021]

avg_package    5
student        6
Name: (cse, 2021), dtype: int64

In [5]:
branch_df1['student']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: student, dtype: int64

In [6]:
branch_df2=pd.DataFrame([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11],
    [12,13,14,15]],
    index=[2019,2020,2021,2022],
    columns=pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','student']]))
branch_df2

           delhi              mumbai
     avg_package student avg_package student
2019           1       2           3       4
2020           4       5           6       7
2021           8       9          10      11
2022          12      13          14      15

In [7]:
branch_df2.iloc[3,3]

np.int64(15)

In [8]:
branch_df2.loc[2021,('delhi','student')]

np.int64(9)

In [9]:
branch_df2.loc[2022,('mumbai','avg_package')]

np.int64(14)

In [10]:
branch_df2['mumbai','avg_package']

2019     3
2020     6
2021    10
2022    14
Name: (mumbai, avg_package), dtype: int64

In [11]:
branch_df2.loc[2022]

delhi   avg_package    12
        student        13
mumbai  avg_package    14
        student        15
Name: 2022, dtype: int64

In [12]:
branch_df3=pd.DataFrame([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11],
    [12,13,14,15],
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11],
    [12,13,14,15]],
   index=multiindex,
   columns=pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','student']]))
branch_df3

               delhi              mumbai
         avg_package student avg_package student
cse 2019           1       2           3       4
    2020           4       5           6       7
    2021           8       9          10      11
    2022          12      13          14      15
ece 2019           1       2           3       4
    2020           4       5           6       7
    2021           8       9          10      11
    2022          12      13          14      15

In [36]:
branch_df3.loc[('cse',2021),('delhi','student')]
branch_df3.iloc[2,1]

np.int64(9)

In [38]:
branch_df3['delhi','student']
branch_df3.loc['cse',2021]

delhi   avg_package     8
        student         9
mumbai  avg_package    10
        student        11
Name: (cse, 2021), dtype: int64

In [15]:
branch_df1

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ece 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [16]:
branch_df1.unstack()

    avg_package                student
           2019 2020 2021 2022    2019 2020 2021 2022
cse           1    3    5    7       2    4    6    8
ece           9   11   13   15      10   12   14   16

In [40]:
branch_df1.unstack().unstack()

avg_package  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
student      2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [42]:
branch_df1.unstack().unstack().unstack().unstack().unstack()

cse  2019  avg_package     1
           student         2
     2020  avg_package     3
           student         4
     2021  avg_package     5
           student         6
     2022  avg_package     7
           student         8
ece  2019  avg_package     9
           student        10
     2020  avg_package    11
           student        12
     2021  avg_package    13
           student        14
     2022  avg_package    15
           student        16
dtype: int64

In [19]:
branch_df1.unstack().unstack().unstack().unstack().unstack().unstack()

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ece 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [20]:
branch_df1.unstack().stack()

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ece 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [21]:
branch_df1.unstack().stack().stack()

cse  2019  avg_package     1
           student         2
     2020  avg_package     3
           student         4
     2021  avg_package     5
           student         6
     2022  avg_package     7
           student         8
ece  2019  avg_package     9
           student        10
     2020  avg_package    11
           student        12
     2021  avg_package    13
           student        14
     2022  avg_package    15
           student        16
dtype: int64

In [22]:
branch_df2

           delhi              mumbai
     avg_package student avg_package student
2019           1       2           3       4
2020           4       5           6       7
2021           8       9          10      11
2022          12      13          14      15

In [23]:
branch_df1.unstack()

    avg_package                student
           2019 2020 2021 2022    2019 2020 2021 2022
cse           1    3    5    7       2    4    6    8
ece           9   11   13   15      10   12   14   16

In [43]:
branch_df3

               delhi              mumbai
         avg_package student avg_package student
cse 2019           1       2           3       4
    2020           4       5           6       7
    2021           8       9          10      11
    2022          12      13          14      15
ece 2019           1       2           3       4
    2020           4       5           6       7
    2021           8       9          10      11
    2022          12      13          14      15

In [24]:
branch_df3.unstack()

          delhi                                            mumbai            \
    avg_package                student                avg_package
           2019 2020 2021 2022    2019 2020 2021 2022        2019 2020 2021
cse           1    4    8   12       2    5    9   13           3    6   10
ece           1    4    8   12       2    5    9   13           3    6   10


         student
    2022    2019 2020 2021 2022
cse   14       4    7   11   15
ece   14       4    7   11   15

In [25]:
branch_df1

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ece 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [26]:
branch_df1.stack()

cse  2019  avg_package     1
           student         2
     2020  avg_package     3
           student         4
     2021  avg_package     5
           student         6
     2022  avg_package     7
           student         8
ece  2019  avg_package     9
           student        10
     2020  avg_package    11
           student        12
     2021  avg_package    13
           student        14
     2022  avg_package    15
           student        16
dtype: int64

In [27]:
branch_df2

           delhi              mumbai
     avg_package student avg_package student
2019           1       2           3       4
2020           4       5           6       7
2021           8       9          10      11
2022          12      13          14      15

In [28]:
branch_df2.stack()

                  delhi  mumbai
2019 avg_package      1       3
     student          2       4
2020 avg_package      4       6
     student          5       7
2021 avg_package      8      10
     student          9      11
2022 avg_package     12      14
     student         13      15

In [29]:
branch_df3

               delhi              mumbai
         avg_package student avg_package student
cse 2019           1       2           3       4
    2020           4       5           6       7
    2021           8       9          10      11
    2022          12      13          14      15
ece 2019           1       2           3       4
    2020           4       5           6       7
    2021           8       9          10      11
    2022          12      13          14      15

In [30]:
branch_df3.stack()

                      delhi  mumbai
cse 2019 avg_package      1       3
         student          2       4
    2020 avg_package      4       6
         student          5       7
    2021 avg_package      8      10
         student          9      11
    2022 avg_package     12      14
         student         13      15
ece 2019 avg_package      1       3
         student          2       4
    2020 avg_package      4       6
         student          5       7
    2021 avg_package      8      10
         student          9      11
    2022 avg_package     12      14
         student         13      15

In [45]:
#head and tail
branch_df3.head()
branch_df3.tail()

               delhi              mumbai
         avg_package student avg_package student
cse 2022          12      13          14      15
ece 2019           1       2           3       4
    2020           4       5           6       7
    2021           8       9          10      11
    2022          12      13          14      15

In [32]:
#shape
branch_df3.shape

(8, 4)

In [33]:
#info
branch_df3.info()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int64
 1   (delhi, student)       8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, student)      8 non-null      int64
dtypes: int64(4)
memory usage: 820.0+ bytes

In [47]:
#duplicated->isnull
branch_df3.duplicated()
branch_df3.isnull()

               delhi              mumbai
         avg_package student avg_package student
cse 2019       False   False       False   False
    2020       False   False       False   False
    2021       False   False       False   False
    2022       False   False       False   False
ece 2019       False   False       False   False
    2020       False   False       False   False
    2021       False   False       False   False
    2022       False   False       False   False