In [1]:
import pandas as pd

In [2]:
multiindex=pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [3]:
branch_df3=pd.DataFrame([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]],index=multiindex,columns=pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','student']]))
branch_df3

               delhi              mumbai
         avg_package student avg_package student
cse 2019           1       2           3       4
    2020           1       2           3       4
    2021           1       2           3       4
    2022           1       2           3       4
ece 2019           1       2           3       4
    2020           1       2           3       4
    2021           1       2           3       4
    2022           1       2           3       4

In [4]:
branch_df3.sort_index(ascending=False)

               delhi              mumbai
         avg_package student avg_package student
ece 2022           1       2           3       4
    2021           1       2           3       4
    2020           1       2           3       4
    2019           1       2           3       4
cse 2022           1       2           3       4
    2021           1       2           3       4
    2020           1       2           3       4
    2019           1       2           3       4

In [5]:
branch_df3.sort_index(ascending=[False,True])

               delhi              mumbai
         avg_package student avg_package student
ece 2019           1       2           3       4
    2020           1       2           3       4
    2021           1       2           3       4
    2022           1       2           3       4
cse 2019           1       2           3       4
    2020           1       2           3       4
    2021           1       2           3       4
    2022           1       2           3       4

In [6]:
branch_df3.sort_index(level=1,ascending=False)

               delhi              mumbai
         avg_package student avg_package student
ece 2022           1       2           3       4
cse 2022           1       2           3       4
ece 2021           1       2           3       4
cse 2021           1       2           3       4
ece 2020           1       2           3       4
cse 2020           1       2           3       4
ece 2019           1       2           3       4
cse 2019           1       2           3       4

In [7]:
branch_df3.transpose()

                    cse                 ece
                   2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_package    1    1    1    1    1    1    1    1
       student        2    2    2    2    2    2    2    2
mumbai avg_package    3    3    3    3    3    3    3    3
       student        4    4    4    4    4    4    4    4

In [8]:
branch_df3.swaplevel()

               delhi              mumbai
         avg_package student avg_package student
2019 cse           1       2           3       4
2020 cse           1       2           3       4
2021 cse           1       2           3       4
2022 cse           1       2           3       4
2019 ece           1       2           3       4
2020 ece           1       2           3       4
2021 ece           1       2           3       4
2022 ece           1       2           3       4

In [9]:
branch_df3.swaplevel(axis=1)

         avg_package student avg_package student
               delhi   delhi      mumbai  mumbai
cse 2019           1       2           3       4
    2020           1       2           3       4
    2021           1       2           3       4
    2022           1       2           3       4
ece 2019           1       2           3       4
    2020           1       2           3       4
    2021           1       2           3       4
    2022           1       2           3       4

In [10]:
#melt->simple example brach
#wide to long
pd.DataFrame({'cse':[120]})

   cse
0  120

In [11]:
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [12]:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[200]}).melt()

  variable  value
0      cse    120
1      ece    100
2     mech    200

In [13]:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[200]}).melt(var_name='branch',value_name='num_students')

  branch  num_students
0    cse           120
1    ece           100
2   mech           200

In [14]:
pd.DataFrame(
    {
        'branch':['cse','ese','mech'],
        '2020':[120,140,450],
        '2021':[120,240,450],
        '2022':[150,140,350]
    }).melt()

   variable value
0    branch   cse
1    branch   ese
2    branch  mech
3      2020   120
4      2020   140
5      2020   450
6      2021   120
7      2021   240
8      2021   450
9      2022   150
10     2022   140
11     2022   350

In [15]:
pd.DataFrame(
    {
        'branch':['cse','ese','mech'],
        '2020':[120,140,450],
        '2021':[120,240,450],
        '2022':[150,140,350]
    }).melt(id_vars=['branch'],var_name='year',value_name='students')

  branch  year  students
0    cse  2020       120
1    ese  2020       140
2   mech  2020       450
3    cse  2021       120
4    ese  2021       240
5   mech  2021       450
6    cse  2022       150
7    ese  2022       140
8   mech  2022       350

In [16]:
#need of melt->=for converting data from wide to long
death=pd.read_csv('time_series_covid19_confirmed_global.csv.xls')
death

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,703228,703228,703228,703228,703228,703228,703228,703228,703228,703228
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,535
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,11945,11945,11945,11945,11945,11945,11945,11945,11945,11945
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,334021,334021,334066,334108,334196,334294,334425,334425,334629,334661
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,259981,259981,259981,259981,259981,259981,259981,259981,259981,259981

In [18]:
death.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095