In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
# what are vectorized operations

In [5]:
ages=np.array([22,38,26,35])
ages+4

array([26, 42, 30, 39])

In [6]:
# problem i vectorized operations in vanilla python

In [7]:
names=['jack','anna','john','mary']

In [8]:
# [name.startwith('j')for name in names]

In [9]:
# how pandas solve this issue?

In [11]:
df['Name'].str.startswith('A')

0      False
1      False
2      False
3      False
4       True
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [12]:
# fast and optimized

In [13]:
# common functions

In [14]:
df['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [15]:
df['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [16]:
df['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [17]:
df['Name'].str.title()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [18]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [19]:
df['Name'].str.len().value_counts

<bound method IndexOpsMixin.value_counts of 0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64>

In [20]:
# strip

In [21]:
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [24]:
# split

In [25]:
df['Name'].str.split(',').head()

0                           [Braund,  Mr. Owen Harris]
1    [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                            [Heikkinen,  Miss. Laina]
3      [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                          [Allen,  Mr. William Henry]
Name: Name, dtype: object

In [26]:
# spilt+expand

In [27]:
df['Name'].str.split(',',expand=True).head()

           0                                            1
0     Braund                              Mr. Owen Harris
1    Cumings   Mrs. John Bradley (Florence Briggs Thayer)
2  Heikkinen                                  Miss. Laina
3   Futrelle           Mrs. Jacques Heath (Lily May Peel)
4      Allen                            Mr. William Henry

In [28]:
df['Name'].str.title().value_counts().head(10)

Name
Braund, Mr. Owen Harris                                1
Cumings, Mrs. John Bradley (Florence Briggs Thayer)    1
Heikkinen, Miss. Laina                                 1
Futrelle, Mrs. Jacques Heath (Lily May Peel)           1
Allen, Mr. William Henry                               1
Moran, Mr. James                                       1
Mccarthy, Mr. Timothy J                                1
Palsson, Master. Gosta Leonard                         1
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)      1
Nasser, Mrs. Nicholas (Adele Achem)                    1
Name: count, dtype: int64

In [29]:
#reaplace

In [30]:
df['Name'].str.replace('Mr.','Mr',regex=False).head()

0                               Braund, Mr Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr William Henry
Name: Name, dtype: str

In [31]:
df['Name'].str.replace('Miss.','Miss',regex=False).head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [32]:
# filtering

In [33]:
df[df['Name'].str.startswith('A',na=False)][['Name']].head(10)

                                                  Name
4                             Allen, Mr. William Henry
13                         Andersson, Mr. Anders Johan
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
49       Arnold-Franchi, Mrs. Josef (Josefine Franchi)
68                     Andersson, Miss. Erna Alexandra
91                          Andreasson, Mr. Paul Edvin
114                              Attalah, Miss. Malake
119                  Andersson, Miss. Ellis Anna Maria
144                         Andrew, Mr. Edgardo Samuel

In [34]:
df[df['Name'].str.endswith('n',na=False)][['Name']].head(10)

                               Name
13      Andersson, Mr. Anders Johan
23     Sloper, Mr. William Thompson
45         Rogers, Mr. William John
60            Sirayanian, Mr. Orsen
75          Moen, Mr. Sigurd Hansen
76                Staneff, Mr. Ivan
88       Fortune, Miss. Mabel Helen
91       Andreasson, Mr. Paul Edvin
107          Moss, Mr. Albert Johan
110  Porter, Mr. Walter Chamberlain

In [35]:
# isdigit/isalpha

In [36]:
df[df['Ticket'].str.isdigit()][['Ticket','Name']].head(10)

    Ticket                                               Name
3   113803       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4   373450                           Allen, Mr. William Henry
5   330877                                   Moran, Mr. James
6    17463                            McCarthy, Mr. Timothy J
7   349909                     Palsson, Master. Gosta Leonard
8   347742  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9   237736                Nasser, Mrs. Nicholas (Adele Achem)
11  113783                           Bonnell, Miss. Elizabeth
13  347082                        Andersson, Mr. Anders Johan
14  350406               Vestrom, Miss. Hulda Amanda Adolfina

In [37]:
df[df['Name'].str.isalpha()][['Name']].head(10)

Empty DataFrame
Columns: [Name]
Index: []

In [38]:
# applying regex

In [40]:
#contains

In [41]:
df[df['Name'].str.contains('john',case=False,na=False)][['Name']].head()

                                                 Name
1   Cumings, Mrs. John Bradley (Florence Briggs Th...
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
41  Turpin, Mrs. William John Robert (Dorothy Ann ...
45                           Rogers, Mr. William John
98               Doling, Mrs. John T (Ada Julia Bone)

In [42]:
#search"john"+both case

In [45]:
df[df['Name'].str.contains('john',case=True,na=False)][['Name']].head(10)

Empty DataFrame
Columns: [Name]
Index: []

In [46]:
df[df['Name'].str.contains('john',case=False,na=False)][['Name']].head(10)

                                                  Name
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
41   Turpin, Mrs. William John Robert (Dorothy Ann ...
45                            Rogers, Mr. William John
98                Doling, Mrs. John T (Ada Julia Bone)
112                             Barton, Mr. David John
117                    Turpin, Mr. William John Robert
160                           Cribb, Mr. John Hatfield
162                         Bengtsson, Mr. John Viktor
165    Goldsmith, Master. Frank John William "Frankie"

In [47]:
# regex pattern

In [48]:
df[df['Name'].str.contains(r'^[^,]+,\S*j',regex=True,na=False)][['Name']].head()

Empty DataFrame
Columns: [Name]
Index: []

In [49]:
# contains

In [50]:
df[df['Name'].str.contains('Mrs',case=False,na=False)][['Name']].head()

                                                 Name
1   Cumings, Mrs. John Bradley (Florence Briggs Th...
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                 Nasser, Mrs. Nicholas (Adele Achem)
15                   Hewlett, Mrs. (Mary D Kingcome)

In [51]:
# slicing

In [53]:
df['Name'].str[:10].head()

0    Braund, Mr
1    Cumings, M
2    Heikkinen,
3    Futrelle,
4    Allen, Mr.
Name: Name, dtype: str

In [54]:
df['Name'].str[1:8].head()

0    raund,
1    umings,
2    eikkine
3    utrelle
4    llen, M
Name: Name, dtype: str