# Pandas Practical-4 Integrated Programs

# PROGRAM 1:IPL DATASET-BASIC EXPLORATION

**code:**

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data=pd.read_csv('matches - matches (1).csv.xls')

In [4]:
data

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [5]:
data.head(3)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN

In [6]:
data.tail()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [7]:
data.shape

(636, 18)

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    str
 3   date             636 non-null    str
 4   team1            636 non-null    str
 5   team2            636 non-null    str
 6   toss_winner      636 non-null    str
 7   toss_decision    636 non-null    str
 8   result           636 non-null    str
 9   dl_applied       636 non-null    int64
 10  winner           633 non-null    str
 11  win_by_runs      636 non-null    int64
 12  win_by_wickets   636 non-null    int64
 13  player_of_match  633 non-null    str
 14  venue            636 non-null    str
 15  umpire1          635 non-null    str
 16  umpire2          635 non-null    str
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), str(12)
memory usage: 89.6 KB

In [9]:
data.describe()

,id,season,dl_applied,win_by_runs,win_by_wickets,umpire3
count,636.000000,636.000000,636.000000,636.000000,636.000000,0.0
mean,318.500000,2012.490566,0.025157,13.682390,3.372642,NaN
std,183.741666,2.773026,0.156726,23.908877,3.420338,NaN
min,1.000000,2008.000000,0.000000,0.000000,0.000000,NaN
25%,159.750000,2010.000000,0.000000,0.000000,0.000000,NaN
50%,318.500000,2012.000000,0.000000,0.000000,4.000000,NaN
75%,477.250000,2015.000000,0.000000,20.000000,7.000000,NaN
max,636.000000,2017.000000,1.000000,146.000000,10.000000,NaN

In [10]:
data.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='str')

In [ ]:
print("Dataframe type:",type(data))

Dataframe type: <class 'pandas.DataFrame'>

In [12]:
print("winner column type:",type(data["winner"]))

winner column type: <class 'pandas.Series'>

In [13]:
data['winner']

0              Sunrisers Hyderabad
1           Rising Pune Supergiant
2            Kolkata Knight Riders
3                  Kings XI Punjab
4      Royal Challengers Bangalore
                  ...
631    Royal Challengers Bangalore
632    Royal Challengers Bangalore
633            Sunrisers Hyderabad
634            Sunrisers Hyderabad
635            Sunrisers Hyderabad
Name: winner, Length: 636, dtype: str

**concepts:read_csv(),head(),tail(),shape,info(),describe(),columns,type(),single-column selections.**

**PROGRAM 2:SELECTING COLUMNS AND ROWS USING loc AND iloc**

**code:**

In [14]:
import pandas as pd

In [15]:
data["id"]

0        1
1        2
2        3
3        4
4        5
      ...
631    632
632    633
633    634
634    635
635    636
Name: id, Length: 636, dtype: int64

In [16]:
data[["team1","team2","winner"]]

,team1,team2,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore
...,...,...,...
631,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore
632,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore
633,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad
634,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
635,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad

In [17]:
data.iloc[0]

id                                                         1
season                                                  2017
city                                               Hyderabad
date                                              2017-04-05
team1                                    Sunrisers Hyderabad
team2                            Royal Challengers Bangalore
toss_winner                      Royal Challengers Bangalore
toss_decision                                          field
result                                                normal
dl_applied                                                 0
winner                                   Sunrisers Hyderabad
win_by_runs                                               35
win_by_wickets                                             0
player_of_match                                 Yuvraj Singh
venue              Rajiv Gandhi International Stadium, Uppal
umpire1                                          AY Dandekar
umpire2                                             NJ Llong
umpire3                                                  NaN
Name: 0, dtype: object

In [18]:
data.iloc[1:11]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
6,7,2017,Mumbai,2017-04-09,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
7,8,2017,Indore,2017-04-10,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
9,10,2017,Mumbai,2017-04-12,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
10,11,2017,Kolkata,2017-04-13,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN

In [19]:
data.iloc[[1,5,8]]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN

In [20]:
data.iloc[:,[4,5,10]]

,team1,team2,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore
...,...,...,...
631,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore
632,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore
633,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad
634,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
635,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad

In [21]:
data.loc[0:4,["team1","team2","winner"]]

,team1,team2,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore

In [22]:
data.loc[data["city"]=="Hyderabad"]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
18,19,2017,Hyderabad,2017-04-17,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN
20,21,2017,Hyderabad,2017-04-19,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,15,0,KS Williamson,"Rajiv Gandhi International Stadium, Uppal",CB Gaffaney,NJ Llong,NaN
35,36,2017,Hyderabad,2017-04-30,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,48,0,DA Warner,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,S Ravi,NaN
42,43,2017,Hyderabad,2017-05-06,Rising Pune Supergiant,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Rising Pune Supergiant,12,0,JD Unadkat,"Rajiv Gandhi International Stadium, Uppal",KN Ananthapadmanabhan,AK Chaudhary,NaN
46,47,2017,Hyderabad,2017-05-08,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,normal,0,Sunrisers Hyderabad,0,7,S Dhawan,"Rajiv Gandhi International Stadium, Uppal",KN Ananthapadmanabhan,M Erasmus,NaN
58,59,2017,Hyderabad,2017-05-21,Mumbai Indians,Rising Pune Supergiant,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,KH Pandya,"Rajiv Gandhi International Stadium, Uppal",NJ Llong,S Ravi,NaN
65,66,2008,Hyderabad,2008-04-22,Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,normal,0,Delhi Daredevils,0,9,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",IL Howell,AM Saheba,NaN
67,68,2008,Hyderabad,2008-04-24,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,3,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,MR Benson,NaN
76,77,2008,Hyderabad,2008-05-01,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,7,SE Marsh,"Rajiv Gandhi International Stadium, Uppal",BR Doctrove,RB Tiffin,NaN
79,80,2008,Hyderabad,2008-05-25,Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers,bat,normal,0,Royal Challengers Bangalore,0,5,R Vinay Kumar,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,RE Koertzen,NaN
91,92,2008,Hyderabad,2008-05-11,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,23,0,SC Ganguly,"Rajiv Gandhi International Stadium, Uppal",IL Howell,AM Saheba,NaN
101,102,2008,Hyderabad,2008-05-18,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,normal,0,Mumbai Indians,25,0,DJ Bravo,"Rajiv Gandhi International Stadium, Uppal",BR Doctrove,DJ Harper,NaN
113,114,2008,Hyderabad,2008-05-27,Deccan Chargers,Chennai Super Kings,Deccan Chargers,bat,normal,0,Chennai Super Kings,0,7,SK Raina,"Rajiv Gandhi International Stadium, Uppal",BG Jerling,AM Saheba,NaN
235,236,2011,Hyderabad,2011-04-09,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,8,SK Trivedi,"Rajiv Gandhi International Stadium, Uppal",RE Koertzen,SK Tarapore,NaN
244,245,2011,Hyderabad,2011-04-14,Deccan Chargers,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Deccan Chargers,33,0,DW Steyn,"Rajiv Gandhi International Stadium, Uppal",RE Koertzen,S Ravi,NaN
248,249,2011,Hyderabad,2011-04-16,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,8,PC Valthaty,"Rajiv Gandhi International Stadium, Uppal",RE Koertzen,S Ravi,NaN
259,260,2011,Hyderabad,2011-04-24,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,normal,0,Mumbai Indians,37,0,SL Malinga,"Rajiv Gandhi International Stadium, Uppal",HDPK Dharmasena,AL Hill,NaN
274,275,2011,Hyderabad,2011-05-03,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,field,normal,0,Kolkata Knight Riders,20,0,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",S Asnani,RJ Tucker,NaN
278,279,2011,Hyderabad,2011-05-05,Deccan Chargers,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,4,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,AM Saheba,NaN
285,286,2011,Hyderabad,2011-05-10,Deccan Chargers,Pune Warriors,Deccan Chargers,bat,normal,0,Pune Warriors,0,6,MR Marsh,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,AM Saheba,NaN
330,331,2012,Hyderabad,2012-05-10,Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,normal,0,Delhi Daredevils,0,9,DA Warner,"Rajiv Gandhi International Stadium, Uppal",JD Cloete,SJA Taufel,NaN
358,359,2012,Hyderabad,2012-05-08,Kings XI Punjab,Deccan Chargers,Deccan Chargers,field,normal,0,Kings XI Punjab,25,0,Mandeep Singh,"Rajiv Gandhi International Stadium, Uppal",HDPK Dharmasena,BNJ Oxenford,NaN
372,373,2012,Hyderabad,2012-05-18,Rajasthan Royals,Deccan Chargers,Rajasthan Royals,bat,normal,0,Deccan Chargers,0,5,DW Steyn,"Rajiv Gandhi International Stadium, Uppal",S Ravi,SJA Taufel,NaN
375,376,2012,Hyderabad,2012-05-20,Deccan Chargers,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Deccan Chargers,9,0,DW Steyn,"Rajiv Gandhi International Stadium, Uppal",S Ravi,SJA Taufel,NaN
383,384,2013,Hyderabad,2013-04-05,Sunrisers Hyderabad,Pune Warriors,Pune Warriors,field,normal,0,Sunrisers Hyderabad,22,0,A Mishra,"Rajiv Gandhi International Stadium, Uppal",S Ravi,SJA Taufel,NaN
387,388,2013,Hyderabad,2013-04-07,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,bat,tie,0,Sunrisers Hyderabad,0,0,GH Vihari,"Rajiv Gandhi International Stadium, Uppal",AK Chaudhary,S Ravi,NaN
404,405,2013,Hyderabad,2013-04-19,Kings XI Punjab,Sunrisers Hyderabad,Kings XI Punjab,bat,normal,0,Sunrisers Hyderabad,0,5,GH Vihari,"Rajiv Gandhi International Stadium, Uppal",HDPK Dharmasena,CK Nandan,NaN
422,423,2013,Hyderabad,2013-05-01,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,normal,0,Sunrisers Hyderabad,0,7,I Sharma,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,S Asnani,NaN
427,428,2013,Hyderabad,2013-05-04,Delhi Daredevils,Sunrisers Hyderabad,Delhi Daredevils,bat,normal,0,Sunrisers Hyderabad,0,6,DJG Sammy,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,S Asnani,NaN
434,435,2013,Hyderabad,2013-05-08,Chennai Super Kings,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Chennai Super Kings,77,0,SK Raina,"Rajiv Gandhi International Stadium, Uppal",S Das,NJ Llong,NaN
448,449,2013,Hyderabad,2013-05-17,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,23,0,A Mishra,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,AK Chaudhary,NaN
452,453,2013,Hyderabad,2013-05-19,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders,bat,normal,0,Sunrisers Hyderabad,0,5,PA Patel,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,S Asnani,NaN
492,493,2014,Hyderabad,2014-05-12,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad,bat,normal,0,Mumbai Indians,0,7,AT Rayudu,"Rajiv Gandhi International Stadium, Uppal",HDPK Dharmasena,VA Kulkarni,NaN
495,496,2014,Hyderabad,2014-05-14,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,WP Saha,"Rajiv Gandhi International Stadium, Uppal",VA Kulkarni,PG Pathak,NaN
499,500,2014,Hyderabad,2014-05-18,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,normal,0,Kolkata Knight Riders,0,7,UT Yadav,"Rajiv Gandhi International Stadium, Uppal",NJ Llong,CK Nandan,NaN
502,503,2014,Hyderabad,2014-05-20,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,bat,normal,0,Sunrisers Hyderabad,0,7,DA Warner,"Rajiv Gandhi International Stadium, Uppal",AK Chaudhary,NJ Llong,NaN
550,551,2015,Hyderabad,2015-05-02,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,field,normal,0,Sunrisers Hyderabad,22,0,DA Warner,"Rajiv Gandhi International Stadium, Uppal",AK Chaudhary,K Srinivasan,NaN
563,564,2015,Hyderabad,2015-05-11,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,5,0,DA Warner,"Rajiv Gandhi International Stadium, Uppal",AK Chaudhary,HDPK Dharmasena,NaN
567,568,2015,Hyderabad,2015-05-15,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,1,Royal Challengers Bangalore,0,6,V Kohli,"Rajiv Gandhi International Stadium, Uppal",AK Chaudhary,HDPK Dharmasena,NaN
571,572,2015,Hyderabad,2015-05-17,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad,bat,normal,0,Mumbai Indians,0,9,MJ McClenaghan,"Rajiv Gandhi International Stadium, Uppal",CB Gaffaney,K Srinath,NaN
583,584,2016,Hyderabad,2016-04-16,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,normal,0,Kolkata Knight Riders,0,8,G Gambhir,"Rajiv Gandhi International Stadium, Uppal",AK Chaudhary,CK Nandan,NaN
587,588,2016,Hyderabad,2016-04-18,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,7,DA Warner,"Rajiv Gandhi International Stadium, Uppal",HDPK Dharmasena,VK Sharma,NaN
593,594,2016,Hyderabad,2016-04-23,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,5,Mustafizur Rahman,"Rajiv Gandhi International Stadium, Uppal",AK Chaudhary,CK Nandan,NaN
597,598,2016,Hyderabad,2016-04-26,Sunrisers Hyderabad,Rising Pune Supergiants,Rising Pune Supergiants,field,normal,1,Rising Pune Supergiants,34,0,AB Dinda,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,CK Nandan,NaN
602,603,2016,Hyderabad,2016-04-30,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,15,0,DA Warner,"Rajiv Gandhi International Stadium, Uppal",AK Chaudhary,HDPK Dharmasena,NaN
609,610,2016,Hyderabad,2016-05-06,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,5,B Kumar,"Rajiv Gandhi International Stadium, Uppal",M Erasmus,S Ravi,NaN
617,618,2016,Hyderabad,2016-05-12,Sunrisers Hyderabad,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,7,CH Morris,"Rajiv Gandhi International Stadium, Uppal",K Bharatan,M Erasmus,NaN

In [23]:
data.loc[data["city"]=="Hyderabad",["season","team1","team2","winner"]]

,season,team1,team2,winner
0,2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
5,2017,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
18,2017,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad
20,2017,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad
35,2017,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad
42,2017,Rising Pune Supergiant,Sunrisers Hyderabad,Rising Pune Supergiant
46,2017,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad
58,2017,Mumbai Indians,Rising Pune Supergiant,Mumbai Indians
65,2008,Deccan Chargers,Delhi Daredevils,Delhi Daredevils
67,2008,Deccan Chargers,Rajasthan Royals,Rajasthan Royals
76,2008,Deccan Chargers,Kings XI Punjab,Kings XI Punjab
79,2008,Deccan Chargers,Royal Challengers Bangalore,Royal Challengers Bangalore
91,2008,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
101,2008,Mumbai Indians,Deccan Chargers,Mumbai Indians
113,2008,Deccan Chargers,Chennai Super Kings,Chennai Super Kings
235,2011,Deccan Chargers,Rajasthan Royals,Rajasthan Royals
244,2011,Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers
248,2011,Deccan Chargers,Kings XI Punjab,Kings XI Punjab
259,2011,Mumbai Indians,Deccan Chargers,Mumbai Indians
274,2011,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
278,2011,Deccan Chargers,Delhi Daredevils,Delhi Daredevils
285,2011,Deccan Chargers,Pune Warriors,Pune Warriors
330,2012,Deccan Chargers,Delhi Daredevils,Delhi Daredevils
358,2012,Kings XI Punjab,Deccan Chargers,Kings XI Punjab
372,2012,Rajasthan Royals,Deccan Chargers,Deccan Chargers
375,2012,Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers
383,2013,Sunrisers Hyderabad,Pune Warriors,Sunrisers Hyderabad
387,2013,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad
404,2013,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad
422,2013,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad
427,2013,Delhi Daredevils,Sunrisers Hyderabad,Sunrisers Hyderabad
434,2013,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings
448,2013,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad
452,2013,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad
492,2014,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians
495,2014,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab
499,2014,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders
502,2014,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad
550,2015,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad
563,2015,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad
567,2015,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore
571,2015,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians
583,2016,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders
587,2016,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad
593,2016,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad
597,2016,Sunrisers Hyderabad,Rising Pune Supergiants,Rising Pune Supergiants
602,2016,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
609,2016,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
617,2016,Sunrisers Hyderabad,Delhi Daredevils,Delhi Daredevils

**concepts:single/multiple columns,iloc[],row slicing,specific rows,roe-column selection,Boolean sondition.**

**PROGRAM 3:FILTERING,np.where(),SORTING AND value_counts()**

**code**

In [24]:
data["city"].str.contains("Hyderabad",na=False)

0       True
1      False
2      False
3      False
4      False
       ...
631    False
632    False
633    False
634    False
635    False
Name: city, Length: 636, dtype: bool

In [25]:
hyderabad=data[data["city"]=="Hyderabad"]

In [26]:
print(hyderabad)

      id  season       city        date                        team1  \
0      1    2017  Hyderabad  2017-04-05          Sunrisers Hyderabad
5      6    2017  Hyderabad  2017-04-09                Gujarat Lions
18    19    2017  Hyderabad  2017-04-17          Sunrisers Hyderabad
20    21    2017  Hyderabad  2017-04-19          Sunrisers Hyderabad
35    36    2017  Hyderabad  2017-04-30          Sunrisers Hyderabad
42    43    2017  Hyderabad  2017-05-06       Rising Pune Supergiant
46    47    2017  Hyderabad  2017-05-08               Mumbai Indians
58    59    2017  Hyderabad  2017-05-21               Mumbai Indians
65    66    2008  Hyderabad  2008-04-22              Deccan Chargers
67    68    2008  Hyderabad  2008-04-24              Deccan Chargers
76    77    2008  Hyderabad  2008-05-01              Deccan Chargers
79    80    2008  Hyderabad  2008-05-25              Deccan Chargers
91    92    2008  Hyderabad  2008-05-11        Kolkata Knight Riders
101  102    2008  Hyderabad  2008-05-18               Mumbai Indians
113  114    2008  Hyderabad  2008-05-27              Deccan Chargers
235  236    2011  Hyderabad  2011-04-09              Deccan Chargers
244  245    2011  Hyderabad  2011-04-14              Deccan Chargers
248  249    2011  Hyderabad  2011-04-16              Deccan Chargers
259  260    2011  Hyderabad  2011-04-24               Mumbai Indians
274  275    2011  Hyderabad  2011-05-03        Kolkata Knight Riders
278  279    2011  Hyderabad  2011-05-05              Deccan Chargers
285  286    2011  Hyderabad  2011-05-10              Deccan Chargers
330  331    2012  Hyderabad  2012-05-10              Deccan Chargers
358  359    2012  Hyderabad  2012-05-08              Kings XI Punjab
372  373    2012  Hyderabad  2012-05-18             Rajasthan Royals
375  376    2012  Hyderabad  2012-05-20              Deccan Chargers
383  384    2013  Hyderabad  2013-04-05          Sunrisers Hyderabad
387  388    2013  Hyderabad  2013-04-07  Royal Challengers Bangalore
404  405    2013  Hyderabad  2013-04-19              Kings XI Punjab
422  423    2013  Hyderabad  2013-05-01               Mumbai Indians
427  428    2013  Hyderabad  2013-05-04             Delhi Daredevils
434  435    2013  Hyderabad  2013-05-08          Chennai Super Kings
448  449    2013  Hyderabad  2013-05-17          Sunrisers Hyderabad
452  453    2013  Hyderabad  2013-05-19        Kolkata Knight Riders
492  493    2014  Hyderabad  2014-05-12          Sunrisers Hyderabad
495  496    2014  Hyderabad  2014-05-14          Sunrisers Hyderabad
499  500    2014  Hyderabad  2014-05-18          Sunrisers Hyderabad
502  503    2014  Hyderabad  2014-05-20  Royal Challengers Bangalore
550  551    2015  Hyderabad  2015-05-02          Sunrisers Hyderabad
563  564    2015  Hyderabad  2015-05-11          Sunrisers Hyderabad
567  568    2015  Hyderabad  2015-05-15          Sunrisers Hyderabad
571  572    2015  Hyderabad  2015-05-17          Sunrisers Hyderabad
583  584    2016  Hyderabad  2016-04-16          Sunrisers Hyderabad
587  588    2016  Hyderabad  2016-04-18               Mumbai Indians
593  594    2016  Hyderabad  2016-04-23              Kings XI Punjab
597  598    2016  Hyderabad  2016-04-26          Sunrisers Hyderabad
602  603    2016  Hyderabad  2016-04-30          Sunrisers Hyderabad
609  610    2016  Hyderabad  2016-05-06                Gujarat Lions
617  618    2016  Hyderabad  2016-05-12          Sunrisers Hyderabad

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field
5            Sunrisers Hyderabad          Sunrisers Hyderabad         field
18               Kings XI Punjab              Kings XI Punjab         field
20              Delhi Daredevils          Sunrisers Hyderabad           bat
35         Kolkata Knight Riders        Kolkata Knight Riders         field
42           Sunrisers Hyderabad          Sunrisers Hyderabad         field
46           Sunrisers Hyderabad               Mumbai Indians           bat
58        Rising Pune Supergiant               Mumbai Indians           bat
65              Delhi Daredevils              Deccan Chargers           bat
67              Rajasthan Royals             Rajasthan Royals         field
76               Kings XI Punjab              Kings XI Punjab         field
79   Royal Challengers Bangalore              Deccan Chargers           bat
91               Deccan Chargers        Kolkata Knight Riders           bat
101              Deccan Chargers              Deccan Chargers         field
113          Chennai Super Kings              Deccan Chargers           bat
235             Rajasthan Royals             Rajasthan Royals         field
244  Royal Challengers Bangalore  Royal Challengers Bangalore         field
248              Kings XI Punjab              Kings XI Punjab         field
259              Deccan Chargers              Deccan Chargers         field
274              Deccan Chargers              Deccan Chargers         field
278             Delhi Daredevils             Delhi Daredevils         field
285                Pune Warriors              Deccan Chargers           bat
330             Delhi Daredevils              Deccan Chargers           bat
358              Deccan Chargers              Deccan Chargers         field
372              Deccan Chargers             Rajasthan Royals           bat
375  Royal Challengers Bangalore  Royal Challengers Bangalore         field
383                Pune Warriors                Pune Warriors         field
387          Sunrisers Hyderabad  Royal Challengers Bangalore           bat
404          Sunrisers Hyderabad              Kings XI Punjab           bat
422          Sunrisers Hyderabad               Mumbai Indians           bat
427          Sunrisers Hyderabad             Delhi Daredevils           bat
434          Sunrisers Hyderabad          Sunrisers Hyderabad         field
448             Rajasthan Royals          Sunrisers Hyderabad           bat
452          Sunrisers Hyderabad        Kolkata Knight Riders           bat
492               Mumbai Indians          Sunrisers Hyderabad           bat
495              Kings XI Punjab              Kings XI Punjab         field
499        Kolkata Knight Riders          Sunrisers Hyderabad           bat
502          Sunrisers Hyderabad  Royal Challengers Bangalore           bat
550          Chennai Super Kings          Chennai Super Kings         field
563              Kings XI Punjab          Sunrisers Hyderabad           bat
567  Royal Challengers Bangalore          Sunrisers Hyderabad           bat
571               Mumbai Indians          Sunrisers Hyderabad           bat
583        Kolkata Knight Riders          Sunrisers Hyderabad           bat
587          Sunrisers Hyderabad          Sunrisers Hyderabad         field
593          Sunrisers Hyderabad          Sunrisers Hyderabad         field
597      Rising Pune Supergiants      Rising Pune Supergiants         field
602  Royal Challengers Bangalore  Royal Challengers Bangalore         field
609          Sunrisers Hyderabad          Sunrisers Hyderabad         field
617             Delhi Daredevils             Delhi Daredevils         field

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35
5    normal           0          Sunrisers Hyderabad            0
18   normal           0          Sunrisers Hyderabad            5
20   normal           0          Sunrisers Hyderabad           15
35   normal           0          Sunrisers Hyderabad           48
42   normal           0       Rising Pune Supergiant           12
46   normal           0          Sunrisers Hyderabad            0
58   normal           0               Mumbai Indians            1
65   normal           0             Delhi Daredevils            0
67   normal           0             Rajasthan Royals            0
76   normal           0              Kings XI Punjab            0
79   normal           0  Royal Challengers Bangalore            0
91   normal           0        Kolkata Knight Riders           23
101  normal           0               Mumbai Indians           25
113  normal           0          Chennai Super Kings            0
235  normal           0             Rajasthan Royals            0
244  normal           0              Deccan Chargers           33
248  normal           0              Kings XI Punjab            0
259  normal           0               Mumbai Indians           37
274  normal           0        Kolkata Knight Riders           20
278  normal           0             Delhi Daredevils            0
285  normal           0                Pune Warriors            0
330  normal           0             Delhi Daredevils            0
358  normal           0              Kings XI Punjab           25
372  normal           0              Deccan Chargers            0
375  normal           0              Deccan Chargers            9
383  normal           0          Sunrisers Hyderabad           22
387     tie           0          Sunrisers Hyderabad            0
404  normal           0          Sunrisers Hyderabad            0
422  normal           0          Sunrisers Hyderabad            0
427  normal           0          Sunrisers Hyderabad            0
434  normal           0          Chennai Super Kings           77
448  normal           0          Sunrisers Hyderabad           23
452  normal           0          Sunrisers Hyderabad            0
492  normal           0               Mumbai Indians            0
495  normal           0              Kings XI Punjab            0
499  normal           0        Kolkata Knight Riders            0
502  normal           0          Sunrisers Hyderabad            0
550  normal           0          Sunrisers Hyderabad           22
563  normal           0          Sunrisers Hyderabad            5
567  normal           1  Royal Challengers Bangalore            0
571  normal           0               Mumbai Indians            0
583  normal           0        Kolkata Knight Riders            0
587  normal           0          Sunrisers Hyderabad            0
593  normal           0          Sunrisers Hyderabad            0
597  normal           1      Rising Pune Supergiants           34
602  normal           0          Sunrisers Hyderabad           15
609  normal           0          Sunrisers Hyderabad            0
617  normal           0             Delhi Daredevils            0

     win_by_wickets    player_of_match  \
0                 0       Yuvraj Singh
5                 9        Rashid Khan
18                0            B Kumar
20                0      KS Williamson
35                0          DA Warner
42                0         JD Unadkat
46                7           S Dhawan
58                0          KH Pandya
65                9           V Sehwag
67                3          YK Pathan
76                7           SE Marsh
79                5      R Vinay Kumar
91                0         SC Ganguly
101               0           DJ Bravo
113               7           SK Raina
235               8         SK Trivedi
244               0           DW Steyn
248               8        PC Valthaty
259               0         SL Malinga
274               0          YK Pathan
278               4           V Sehwag
285               6           MR Marsh
330               9          DA Warner
358               0      Mandeep Singh
372               5           DW Steyn
375               0           DW Steyn
383               0           A Mishra
387               0          GH Vihari
404               5          GH Vihari
422               7           I Sharma
427               6          DJG Sammy
434               0           SK Raina
448               0           A Mishra
452               5           PA Patel
492               7          AT Rayudu
495               6            WP Saha
499               7           UT Yadav
502               7          DA Warner
550               0          DA Warner
563               0          DA Warner
567               6            V Kohli
571               9     MJ McClenaghan
583               8          G Gambhir
587               7          DA Warner
593               5  Mustafizur Rahman
597               0           AB Dinda
602               0          DA Warner
609               5            B Kumar
617               7          CH Morris

                                         venue                umpire1  \
0    Rajiv Gandhi International Stadium, Uppal            AY Dandekar
5    Rajiv Gandhi International Stadium, Uppal             A Deshmukh
18   Rajiv Gandhi International Stadium, Uppal            AY Dandekar
20   Rajiv Gandhi International Stadium, Uppal            CB Gaffaney
35   Rajiv Gandhi International Stadium, Uppal            AY Dandekar
42   Rajiv Gandhi International Stadium, Uppal  KN Ananthapadmanabhan
46   Rajiv Gandhi International Stadium, Uppal  KN Ananthapadmanabhan
58   Rajiv Gandhi International Stadium, Uppal               NJ Llong
65   Rajiv Gandhi International Stadium, Uppal              IL Howell
67   Rajiv Gandhi International Stadium, Uppal              Asad Rauf
76   Rajiv Gandhi International Stadium, Uppal            BR Doctrove
79   Rajiv Gandhi International Stadium, Uppal              Asad Rauf
91   Rajiv Gandhi International Stadium, Uppal              IL Howell
101  Rajiv Gandhi International Stadium, Uppal            BR Doctrove
113  Rajiv Gandhi International Stadium, Uppal             BG Jerling
235  Rajiv Gandhi International Stadium, Uppal            RE Koertzen
244  Rajiv Gandhi International Stadium, Uppal            RE Koertzen
248  Rajiv Gandhi International Stadium, Uppal            RE Koertzen
259  Rajiv Gandhi International Stadium, Uppal        HDPK Dharmasena
274  Rajiv Gandhi International Stadium, Uppal               S Asnani
278  Rajiv Gandhi International Stadium, Uppal              Asad Rauf
285  Rajiv Gandhi International Stadium, Uppal              Asad Rauf
330  Rajiv Gandhi International Stadium, Uppal              JD Cloete
358  Rajiv Gandhi International Stadium, Uppal        HDPK Dharmasena
372  Rajiv Gandhi International Stadium, Uppal                 S Ravi
375  Rajiv Gandhi International Stadium, Uppal                 S Ravi
383  Rajiv Gandhi International Stadium, Uppal                 S Ravi
387  Rajiv Gandhi International Stadium, Uppal           AK Chaudhary
404  Rajiv Gandhi International Stadium, Uppal        HDPK Dharmasena
422  Rajiv Gandhi International Stadium, Uppal              Asad Rauf
427  Rajiv Gandhi International Stadium, Uppal              Asad Rauf
434  Rajiv Gandhi International Stadium, Uppal                  S Das
448  Rajiv Gandhi International Stadium, Uppal              Asad Rauf
452  Rajiv Gandhi International Stadium, Uppal              Asad Rauf
492  Rajiv Gandhi International Stadium, Uppal        HDPK Dharmasena
495  Rajiv Gandhi International Stadium, Uppal            VA Kulkarni
499  Rajiv Gandhi International Stadium, Uppal               NJ Llong
502  Rajiv Gandhi International Stadium, Uppal           AK Chaudhary
550  Rajiv Gandhi International Stadium, Uppal           AK Chaudhary
563  Rajiv Gandhi International Stadium, Uppal           AK Chaudhary
567  Rajiv Gandhi International Stadium, Uppal           AK Chaudhary
571  Rajiv Gandhi International Stadium, Uppal            CB Gaffaney
583  Rajiv Gandhi International Stadium, Uppal           AK Chaudhary
587  Rajiv Gandhi International Stadium, Uppal        HDPK Dharmasena
593  Rajiv Gandhi International Stadium, Uppal           AK Chaudhary
597  Rajiv Gandhi International Stadium, Uppal            AY Dandekar
602  Rajiv Gandhi International Stadium, Uppal           AK Chaudhary
609  Rajiv Gandhi International Stadium, Uppal              M Erasmus
617  Rajiv Gandhi International Stadium, Uppal             K Bharatan

             umpire2  umpire3
0           NJ Llong      NaN
5           NJ Llong      NaN
18        A Deshmukh      NaN
20          NJ Llong      NaN
35            S Ravi      NaN
42      AK Chaudhary      NaN
46         M Erasmus      NaN
58            S Ravi      NaN
65         AM Saheba      NaN
67         MR Benson      NaN
76         RB Tiffin      NaN
79       RE Koertzen      NaN
91         AM Saheba      NaN
101        DJ Harper      NaN
113        AM Saheba      NaN
235      SK Tarapore      NaN
244           S Ravi      NaN
248           S Ravi      NaN
259          AL Hill      NaN
274        RJ Tucker      NaN
278        AM Saheba      NaN
285        AM Saheba      NaN
330       SJA Taufel      NaN
358     BNJ Oxenford      NaN
372       SJA Taufel      NaN
375       SJA Taufel      NaN
383       SJA Taufel      NaN
387           S Ravi      NaN
404        CK Nandan      NaN
422         S Asnani      NaN
427         S Asnani      NaN
434         NJ Llong      NaN
448     AK Chaudhary      NaN
452         S Asnani      NaN
492      VA Kulkarni      NaN
495        PG Pathak      NaN
499        CK Nandan      NaN
502         NJ Llong      NaN
550     K Srinivasan      NaN
563  HDPK Dharmasena      NaN
567  HDPK Dharmasena      NaN
571        K Srinath      NaN
583        CK Nandan      NaN
587        VK Sharma      NaN
593        CK Nandan      NaN
597        CK Nandan      NaN
602  HDPK Dharmasena      NaN
609           S Ravi      NaN
617        M Erasmus      NaN

In [27]:
data["win_status"]=np.where(data["win_by_runs"]>0,"won by runs","won by wickets/other")

In [28]:
high_margin=data[data["win_by_runs"]>50]

In [29]:
print(high_margin[["season","winner","win_by_runs"]])

     season                       winner  win_by_runs
8      2017             Delhi Daredevils           97
14     2017             Delhi Daredevils           51
26     2017        Kolkata Knight Riders           82
32     2017       Rising Pune Supergiant           61
43     2017               Mumbai Indians          146
59     2008        Kolkata Knight Riders          140
68     2008              Kings XI Punjab           66
100    2008             Rajasthan Royals           65
114    2008             Rajasthan Royals          105
118    2009  Royal Challengers Bangalore           75
121    2009          Chennai Super Kings           92
131    2009               Mumbai Indians           92
143    2009          Chennai Super Kings           78
144    2009             Rajasthan Royals           78
154    2009              Deccan Chargers           53
181    2010          Chennai Super Kings           55
182    2010               Mumbai Indians           98
202    2010             Delhi Daredevils           67
206    2010               Mumbai Indians           63
225    2010               Mumbai Indians           57
264    2011              Deccan Chargers           55
279    2011  Royal Challengers Bangalore           85
284    2011          Chennai Super Kings           63
286    2011              Kings XI Punjab           76
295    2011              Kings XI Punjab          111
299    2011              Deccan Chargers           82
306    2011          Chennai Super Kings           58
312    2012          Chennai Super Kings           74
325    2012             Rajasthan Royals           59
379    2012          Chennai Super Kings           86
402    2013             Rajasthan Royals           87
403    2013          Chennai Super Kings           86
410    2013  Royal Challengers Bangalore          130
416    2013               Mumbai Indians           58
429    2013               Mumbai Indians           60
433    2013               Mumbai Indians           65
434    2013          Chennai Super Kings           77
464    2014          Chennai Super Kings           93
465    2014              Kings XI Punjab           72
497    2014             Rajasthan Royals           62
541    2015          Chennai Super Kings           97
556    2015  Royal Challengers Bangalore          138
573    2015  Royal Challengers Bangalore           71
612    2016          Sunrisers Hyderabad           85
619    2016  Royal Challengers Bangalore          144
622    2016               Mumbai Indians           80
625    2016  Royal Challengers Bangalore           82

In [30]:
sorted_data=data.sort_values("win_by_runs",ascending=False)

In [31]:
sorted_data[["winner","win_by_runs"]].head(10)

                          winner  win_by_runs
43                Mumbai Indians          146
619  Royal Challengers Bangalore          144
59         Kolkata Knight Riders          140
556  Royal Challengers Bangalore          138
410  Royal Challengers Bangalore          130
295              Kings XI Punjab          111
114             Rajasthan Royals          105
182               Mumbai Indians           98
541          Chennai Super Kings           97
8               Delhi Daredevils           97

In [32]:
data["winner"].value_counts()

winner
Mumbai Indians                 92
Chennai Super Kings            79
Kolkata Knight Riders          77
Royal Challengers Bangalore    73
Kings XI Punjab                70
Rajasthan Royals               63
Delhi Daredevils               62
Sunrisers Hyderabad            42
Deccan Chargers                29
Gujarat Lions                  13
Pune Warriors                  12
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: count, dtype: int64

In [33]:
print(data["city"].value_counts())

city
Mumbai            85
Bangalore         66
Kolkata           61
Delhi             60
Hyderabad         49
Chennai           48
Chandigarh        46
Jaipur            33
Pune              32
Durban            15
Centurion         12
Ahmedabad         12
Visakhapatnam     11
Rajkot            10
Dharamsala         9
Johannesburg       8
Cape Town          7
Port Elizabeth     7
Cuttack            7
Ranchi             7
Abu Dhabi          7
Raipur             6
Sharjah            6
Indore             5
Kochi              5
Kanpur             4
East London        3
Kimberley          3
Nagpur             3
Bloemfontein       2
Name: count, dtype: int64

**concepts:str.contains(),boolean filtering,np.where(),new column,comparison,sort_values(),ascending=False,value_counts().**

# PROGRAM 4:USER-DEFINED FUNCTION+FILTRING+VALUE_COUNTS()|

In [34]:
def get_city_matches(city):
    result=data[data["city"]==city]
    return result

In [35]:
hyderabad_matches=get_city_matches("Indore")

In [36]:
hyderabad_matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,win_status
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,won by wickets/other
7,8,2017,Indore,2017-04-10,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,won by wickets/other
21,22,2017,Indore,2017-04-20,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,JC Buttler,Holkar Cricket Stadium,M Erasmus,C Shamshuddin,NaN,won by wickets/other
289,290,2011,Indore,2011-05-13,Kochi Tuskers Kerala,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,KD Karthik,Holkar Cricket Stadium,S Asnani,RJ Tucker,NaN,won by wickets/other
293,294,2011,Indore,2011-05-15,Rajasthan Royals,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,normal,0,Kochi Tuskers Kerala,0,8,BJ Hodge,Holkar Cricket Stadium,PR Reiffel,RJ Tucker,NaN,won by wickets/other

In [37]:
print("Hyderabad matches:",hyderabad_matches.shape)

Hyderabad matches: (5, 19)

In [38]:
def get_team_wins(team_name):
    result=data[data["winner"]==team_name]
    return result[["season","city","team1","team2","winner"]]

In [39]:
get_team_wins("Sunrisers Hyderabad")

,season,city,team1,team2,winner
0,2017,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
5,2017,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
18,2017,Hyderabad,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad
20,2017,Hyderabad,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad
31,2017,Chandigarh,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad
35,2017,Hyderabad,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad
46,2017,Hyderabad,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad
51,2017,Kanpur,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
383,2013,Hyderabad,Sunrisers Hyderabad,Pune Warriors,Sunrisers Hyderabad
387,2013,Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad
393,2013,Delhi,Delhi Daredevils,Sunrisers Hyderabad,Sunrisers Hyderabad
401,2013,Pune,Sunrisers Hyderabad,Pune Warriors,Sunrisers Hyderabad
404,2013,Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad
422,2013,Hyderabad,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad
427,2013,Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,Sunrisers Hyderabad
439,2013,Chandigarh,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad
448,2013,Hyderabad,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad
452,2013,Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad
468,2014,NaN,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad
476,2014,NaN,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad
486,2014,Ahmedabad,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad
488,2014,Delhi,Delhi Daredevils,Sunrisers Hyderabad,Sunrisers Hyderabad
502,2014,Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad
506,2014,Ranchi,Chennai Super Kings,Sunrisers Hyderabad,Sunrisers Hyderabad
524,2015,Bangalore,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad
536,2015,Visakhapatnam,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad
543,2015,Chandigarh,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad
550,2015,Hyderabad,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad
557,2015,Mumbai,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad
560,2015,Raipur,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad
563,2015,Hyderabad,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad
587,2016,Hyderabad,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad
590,2016,Rajkot,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
593,2016,Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad
602,2016,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
609,2016,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
612,2016,Visakhapatnam,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad
615,2016,Visakhapatnam,Sunrisers Hyderabad,Rising Pune Supergiants,Sunrisers Hyderabad
621,2016,Chandigarh,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad
633,2016,Delhi,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad
634,2016,Delhi,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
635,2016,Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad

In [40]:
winner_count=data["winner"].value_counts()

In [41]:
print(winner_count)

winner
Mumbai Indians                 92
Chennai Super Kings            79
Kolkata Knight Riders          77
Royal Challengers Bangalore    73
Kings XI Punjab                70
Rajasthan Royals               63
Delhi Daredevils               62
Sunrisers Hyderabad            42
Deccan Chargers                29
Gujarat Lions                  13
Pune Warriors                  12
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: count, dtype: int64

In [42]:
print("Most frequent winner:",winner_count.index[0])

Most frequent winner: Mumbai Indians

In [43]:
summary=data[["season","city","team1","team2","winner"]]

In [50]:
summary.head(10)

,season,city,team1,team2,winner
0,2017,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
1,2017,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant
2,2017,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders
3,2017,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab
4,2017,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore
5,2017,Hyderabad,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
6,2017,Mumbai,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians
7,2017,Indore,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab
8,2017,Pune,Delhi Daredevils,Rising Pune Supergiant,Delhi Daredevils
9,2017,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians

**concepts:user_defined function,filtering,return,shape,value_counts(),index[],multiple-column selection,head()>**

In [45]:
num = {
    'name':['raman','gagan','harry'],
    'marks':[500,680,456],
    'address':['gurugram','sirsa','hisar']
}

In [46]:
d = ['a','b','c']

In [47]:
data=pd.DataFrame(num,index=d)
data

    name  marks   address
a  raman    500  gurugram
b  gagan    680     sirsa
c  harry    456     hisar

In [48]:
j=pd.read_csv('ipl-matches.csv.xls')
j

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [49]:
j.loc[j['City']=='Mumbai',['City','Team1','Team2','WinningTeam']]

,City,Team1,Team2,WinningTeam
4,Mumbai,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
5,Mumbai,Delhi Capitals,Mumbai Indians,Mumbai Indians
6,Mumbai,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals
7,Mumbai,Gujarat Titans,Royal Challengers Bangalore,Royal Challengers Bangalore
9,Mumbai,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad
...,...,...,...,...
914,Mumbai,Mumbai Indians,Chennai Super Kings,Mumbai Indians
923,Mumbai,Mumbai Indians,Rajasthan Royals,Mumbai Indians
927,Mumbai,Mumbai Indians,Delhi Daredevils,Mumbai Indians
937,Mumbai,Mumbai Indians,Deccan Chargers,Deccan Chargers
946,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore