# Panramedas-3 Big jupyter Notebook Programs

**concepts used:series,DataFrame,indexing,boolean indexing,isin(),between(),clip(),dropna(),drop_duplicated(),astype(),apply(),copy(),value_counts,sort_values(),mean(),gruopby()and DataFrame methods.**

# Program 1-Student Performance Analysis

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import sys

In [4]:
students = pd.DataFrame({
    "name":["Aman","Riya","Karan","Neha","Aman","simran","Vikas","Pooja","Riya","Mohit","Karan"],
    "marks":[78,92,65,88,78,np.nan,54,92,92,71,65],
    "attendance":[86,95,72,91,86,68,59,95,95,80,72],
    "department":["Data Science","AI","Data Science","AI","Data Science","AI","Data Science","AI","AI","Data Science","AI"],
    })

In [5]:
students.shape

(11, 4)

In [6]:
students.dtypes

name              str
marks         float64
attendance      int64
department        str
dtype: object

In [7]:
students.columns

Index(['name', 'marks', 'attendance', 'department'], dtype='str')

In [8]:
students.index

RangeIndex(start=0, stop=11, step=1)

In [9]:
students.head()

    name  marks  attendance    department
0   Aman   78.0          86  Data Science
1   Riya   92.0          95            AI
2  Karan   65.0          72  Data Science
3   Neha   88.0          91            AI
4   Aman   78.0          86  Data Science

In [10]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        11 non-null     str
 1   marks       10 non-null     float64
 2   attendance  11 non-null     int64
 3   department  11 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 484.0 bytes

In [139]:
marks=students["marks"]
marks

0     78
1     92
2     65
3     88
4     78
5      0
6     54
7     92
8     92
9     71
10    65
Name: marks, dtype: int64

In [12]:
marks=marks.dropna()
marks

0     78.0
1     92.0
2     65.0
3     88.0
4     78.0
6     54.0
7     92.0
8     92.0
9     71.0
10    65.0
Name: marks, dtype: float64

In [13]:
marks.astype("int64")

0     78
1     92
2     65
3     88
4     78
6     54
7     92
8     92
9     71
10    65
Name: marks, dtype: int64

In [14]:
sys.getsizeof(marks)

192

In [15]:
marks[marks>=80]

1    92.0
3    88.0
7    92.0
8    92.0
Name: marks, dtype: float64

In [16]:
marks[marks.between(60,90)]

0     78.0
2     65.0
3     88.0
4     78.0
9     71.0
10    65.0
Name: marks, dtype: float64

In [17]:
marks[marks.isin([65,78,92])]

0     78.0
1     92.0
2     65.0
4     78.0
7     92.0
8     92.0
10    65.0
Name: marks, dtype: float64

In [18]:
marks.value_counts()

marks
92.0    3
78.0    2
65.0    2
88.0    1
54.0    1
71.0    1
Name: count, dtype: int64

In [19]:
marks.value_counts().sort_values()

marks
88.0    1
54.0    1
71.0    1
78.0    2
65.0    2
92.0    3
Name: count, dtype: int64

In [20]:
marks.mean()

np.float64(77.5)

In [140]:
attendance = students["attendance"]
attendance

0     86
1     95
2     72
3     91
4     86
5     68
6     59
7     95
8     95
9     80
10    72
Name: attendance, dtype: int64

In [22]:
attendance.clip(60,90)

0     86
1     90
2     72
3     90
4     86
5     68
6     60
7     90
8     90
9     80
10    72
Name: attendance, dtype: int64

In [23]:
attendance[attendance>85]

0    86
1    95
3    91
4    86
7    95
8    95
Name: attendance, dtype: int64

In [24]:
attendance[attendance.isin([86,91,95])]

0    86
1    95
3    91
4    86
7    95
8    95
Name: attendance, dtype: int64

In [25]:
attendance.between(70,90)

0      True
1     False
2      True
3     False
4      True
5     False
6     False
7     False
8     False
9      True
10     True
Name: attendance, dtype: bool

In [141]:
name_series=students["name"]
name_series

0       Aman
1       Riya
2      Karan
3       Neha
4       Aman
5     simran
6      Vikas
7      Pooja
8       Riya
9      Mohit
10     Karan
Name: name, dtype: str

In [27]:
name_series.duplicated()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8      True
9     False
10     True
Name: name, dtype: bool

In [28]:
name_series.duplicated().sum()

np.int64(3)

In [29]:
name_series.value_counts()

name
Aman      2
Riya      2
Karan     2
Neha      1
simran    1
Vikas     1
Pooja     1
Mohit     1
Name: count, dtype: int64

In [30]:
name_series=marks.copy()

In [31]:
name_series

0     78.0
1     92.0
2     65.0
3     88.0
4     78.0
6     54.0
7     92.0
8     92.0
9     71.0
10    65.0
Name: marks, dtype: float64

In [32]:
name_series.apply(lambda x: x+5)

0     83.0
1     97.0
2     70.0
3     93.0
4     83.0
6     59.0
7     97.0
8     97.0
9     76.0
10    70.0
Name: marks, dtype: float64

In [33]:
name_series.apply(lambda x: "Pass" if x >=40 else "Fail")

0     Pass
1     Pass
2     Pass
3     Pass
4     Pass
6     Pass
7     Pass
8     Pass
9     Pass
10    Pass
Name: marks, dtype: str

In [135]:
students["result"]=students["marks"].apply(lambda x: "Not Available" if pd.isna(x) else ("Excellent" if x >=85 else("Good" if x >=60 else "Needs Improvement")))
students

,name,marks,attendance,department,result,performance_score,high_performer
0,Aman,78,86,Data Science,Good,78,False
1,Riya,92,95,AI,Excellent,92,True
2,Karan,65,72,Data Science,Good,65,False
3,Neha,88,91,AI,Excellent,88,True
4,Aman,78,86,Data Science,Good,78,False
5,simran,0,68,AI,Needs Improvement,0,False
6,Vikas,54,59,Data Science,Needs Improvement,54,False
7,Pooja,92,95,AI,Excellent,92,True
8,Riya,92,95,AI,Excellent,92,True
9,Mohit,71,80,Data Science,Good,71,False
10,Karan,65,72,AI,Good,65,False

In [136]:
students["marks"]=students["marks"].fillna(0).astype("int64")
students

,name,marks,attendance,department,result,performance_score,high_performer
0,Aman,78,86,Data Science,Good,78,False
1,Riya,92,95,AI,Excellent,92,True
2,Karan,65,72,Data Science,Good,65,False
3,Neha,88,91,AI,Excellent,88,True
4,Aman,78,86,Data Science,Good,78,False
5,simran,0,68,AI,Needs Improvement,0,False
6,Vikas,54,59,Data Science,Needs Improvement,54,False
7,Pooja,92,95,AI,Excellent,92,True
8,Riya,92,95,AI,Excellent,92,True
9,Mohit,71,80,Data Science,Good,71,False
10,Karan,65,72,AI,Good,65,False

In [137]:
students["performance_score"]=students["marks"].clip(0,100)
students

,name,marks,attendance,department,result,performance_score,high_performer
0,Aman,78,86,Data Science,Good,78,False
1,Riya,92,95,AI,Excellent,92,True
2,Karan,65,72,Data Science,Good,65,False
3,Neha,88,91,AI,Excellent,88,True
4,Aman,78,86,Data Science,Good,78,False
5,simran,0,68,AI,Needs Improvement,0,False
6,Vikas,54,59,Data Science,Needs Improvement,54,False
7,Pooja,92,95,AI,Excellent,92,True
8,Riya,92,95,AI,Excellent,92,True
9,Mohit,71,80,Data Science,Good,71,False
10,Karan,65,72,AI,Good,65,False

In [138]:
students["high_performer"]=students["marks"]>=80
students

,name,marks,attendance,department,result,performance_score,high_performer
0,Aman,78,86,Data Science,Good,78,False
1,Riya,92,95,AI,Excellent,92,True
2,Karan,65,72,Data Science,Good,65,False
3,Neha,88,91,AI,Excellent,88,True
4,Aman,78,86,Data Science,Good,78,False
5,simran,0,68,AI,Needs Improvement,0,False
6,Vikas,54,59,Data Science,Needs Improvement,54,False
7,Pooja,92,95,AI,Excellent,92,True
8,Riya,92,95,AI,Excellent,92,True
9,Mohit,71,80,Data Science,Good,71,False
10,Karan,65,72,AI,Good,65,False

In [38]:
students[students["marks"]>=80]

,name,marks,attendance,department,result,performance_score,high_performer
1,Riya,92,95,AI,Excellent,92,True
3,Neha,88,91,AI,Excellent,88,True
7,Pooja,92,95,AI,Excellent,92,True
8,Riya,92,95,AI,Excellent,92,True

In [39]:
students[students["department"].isin(["AI","Data Science"])]

,name,marks,attendance,department,result,performance_score,high_performer
0,Aman,78,86,Data Science,Good,78,False
1,Riya,92,95,AI,Excellent,92,True
2,Karan,65,72,Data Science,Good,65,False
3,Neha,88,91,AI,Excellent,88,True
4,Aman,78,86,Data Science,Good,78,False
5,simran,0,68,AI,Not Available,0,False
6,Vikas,54,59,Data Science,Needs Improvement,54,False
7,Pooja,92,95,AI,Excellent,92,True
8,Riya,92,95,AI,Excellent,92,True
9,Mohit,71,80,Data Science,Good,71,False
10,Karan,65,72,AI,Good,65,False

In [40]:
students[students["attendance"].between(75,1000)]

,name,marks,attendance,department,result,performance_score,high_performer
0,Aman,78,86,Data Science,Good,78,False
1,Riya,92,95,AI,Excellent,92,True
3,Neha,88,91,AI,Excellent,88,True
4,Aman,78,86,Data Science,Good,78,False
7,Pooja,92,95,AI,Excellent,92,True
8,Riya,92,95,AI,Excellent,92,True
9,Mohit,71,80,Data Science,Good,71,False

In [41]:
students.drop_duplicates()

,name,marks,attendance,department,result,performance_score,high_performer
0,Aman,78,86,Data Science,Good,78,False
1,Riya,92,95,AI,Excellent,92,True
2,Karan,65,72,Data Science,Good,65,False
3,Neha,88,91,AI,Excellent,88,True
5,simran,0,68,AI,Not Available,0,False
6,Vikas,54,59,Data Science,Needs Improvement,54,False
7,Pooja,92,95,AI,Excellent,92,True
9,Mohit,71,80,Data Science,Good,71,False
10,Karan,65,72,AI,Good,65,False

In [42]:
students["name"].value_counts().head()

name
Aman      2
Riya      2
Karan     2
Neha      1
simran    1
Name: count, dtype: int64

In [43]:
students.sort_values("marks",ascending=False).head()

,name,marks,attendance,department,result,performance_score,high_performer
1,Riya,92,95,AI,Excellent,92,True
7,Pooja,92,95,AI,Excellent,92,True
8,Riya,92,95,AI,Excellent,92,True
3,Neha,88,91,AI,Excellent,88,True
0,Aman,78,86,Data Science,Good,78,False

In [44]:
students.groupby("department")["marks"].mean()

department
AI              71.5
Data Science    69.2
Name: marks, dtype: float64

In [45]:
students

,name,marks,attendance,department,result,performance_score,high_performer
0,Aman,78,86,Data Science,Good,78,False
1,Riya,92,95,AI,Excellent,92,True
2,Karan,65,72,Data Science,Good,65,False
3,Neha,88,91,AI,Excellent,88,True
4,Aman,78,86,Data Science,Good,78,False
5,simran,0,68,AI,Not Available,0,False
6,Vikas,54,59,Data Science,Needs Improvement,54,False
7,Pooja,92,95,AI,Excellent,92,True
8,Riya,92,95,AI,Excellent,92,True
9,Mohit,71,80,Data Science,Good,71,False
10,Karan,65,72,AI,Good,65,False

# Program 2-Movie Data Analysis

In [46]:
import pandas as pd

In [47]:
import numpy as np

In [48]:
import sys

In [49]:
movies=pd.DataFrame({
"title":[
    "Inception","Dangal","3 Idiots","Inception","Pk","Pathaan","Dangal","Thriller","Action","comedy","Action","Drama"
],
    "genre":[
        "Sci-Fi","Drama","Comedy","Sci-Fi","comedy","Action","Drama","Thriller","Action","comedy","Action","Drama"
    ],
    "rating":[8.8,8.4,8.4,8.8,8.1,5.8,8.4,8.2,7.8,8.1,7.0,6.5],
    "year":[2010,2016,2009,2010,2014,2023,2016,2015,2022,2014,2023,2020],
    "collection":[850,2000,460,850,800,1050,2000,110,1200,800,1150,150],
})

In [50]:
movies.shape

(12, 5)

In [51]:
movies.dtypes

title             str
genre             str
rating        float64
year            int64
collection      int64
dtype: object

In [52]:
movies.columns

Index(['title', 'genre', 'rating', 'year', 'collection'], dtype='str')

In [53]:
movies.head()

       title   genre  rating  year  collection
0  Inception  Sci-Fi     8.8  2010         850
1     Dangal   Drama     8.4  2016        2000
2   3 Idiots  Comedy     8.4  2009         460
3  Inception  Sci-Fi     8.8  2010         850
4         Pk  comedy     8.1  2014         800

In [54]:
movies.tail()

       title     genre  rating  year  collection
7   Thriller  Thriller     8.2  2015         110
8     Action    Action     7.8  2022        1200
9     comedy    comedy     8.1  2014         800
10    Action    Action     7.0  2023        1150
11     Drama     Drama     6.5  2020         150

In [55]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       12 non-null     str
 1   genre       12 non-null     str
 2   rating      12 non-null     float64
 3   year        12 non-null     int64
 4   collection  12 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 612.0 bytes

In [151]:
ratings=movies["rating"]
ratings

0     8.8
1     8.4
2     8.4
3     8.8
4     8.1
5     5.8
6     8.4
7     8.2
8     7.8
9     8.1
10    7.0
11    6.5
Name: rating, dtype: float64

In [57]:
ratings[ratings>=8]

0    8.8
1    8.4
2    8.4
3    8.8
4    8.1
6    8.4
7    8.2
9    8.1
Name: rating, dtype: float64

In [58]:
ratings[ratings.between(7,9)]

0     8.8
1     8.4
2     8.4
3     8.8
4     8.1
6     8.4
7     8.2
8     7.8
9     8.1
10    7.0
Name: rating, dtype: float64

In [59]:
ratings[ratings.isin([8.1,8.4,8.8])]

0    8.8
1    8.4
2    8.4
3    8.8
4    8.1
6    8.4
9    8.1
Name: rating, dtype: float64

In [60]:
ratings.value_counts()

rating
8.4    3
8.8    2
8.1    2
5.8    1
8.2    1
7.8    1
7.0    1
6.5    1
Name: count, dtype: int64

In [61]:
ratings.value_counts().sort_values(ascending=False)

rating
8.4    3
8.8    2
8.1    2
5.8    1
8.2    1
7.8    1
7.0    1
6.5    1
Name: count, dtype: int64

In [62]:
ratings.mean()

np.float64(7.858333333333333)

In [152]:
titles=movies["title"]
titles

0     Inception
1        Dangal
2      3 Idiots
3     Inception
4            Pk
5       Pathaan
6        Dangal
7      Thriller
8        Action
9        comedy
10       Action
11        Drama
Name: title, dtype: str

In [153]:
titles.duplicated()

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10     True
11    False
Name: title, dtype: bool

In [65]:
titles.duplicated().sum()

np.int64(3)

In [66]:
titles.drop_duplicates()

0     Inception
1        Dangal
2      3 Idiots
4            Pk
5       Pathaan
7      Thriller
8        Action
9        comedy
11        Drama
Name: title, dtype: str

In [67]:
titles.dropna()

0     Inception
1        Dangal
2      3 Idiots
3     Inception
4            Pk
5       Pathaan
6        Dangal
7      Thriller
8        Action
9        comedy
10       Action
11        Drama
Name: title, dtype: str

In [68]:
titles.value_counts()

title
Inception    2
Dangal       2
Action       2
3 Idiots     1
Pk           1
Pathaan      1
Thriller     1
comedy       1
Drama        1
Name: count, dtype: int64

In [154]:
clean_titles=titles.dropna().copy()
clean_titles

0     Inception
1        Dangal
2      3 Idiots
3     Inception
4            Pk
5       Pathaan
6        Dangal
7      Thriller
8        Action
9        comedy
10       Action
11        Drama
Name: title, dtype: str

In [70]:
clean_titles.apply(lambda x: x.upper())

0     INCEPTION
1        DANGAL
2      3 IDIOTS
3     INCEPTION
4            PK
5       PATHAAN
6        DANGAL
7      THRILLER
8        ACTION
9        COMEDY
10       ACTION
11        DRAMA
Name: title, dtype: str

In [71]:
clean_titles.apply(lambda x: x.upper())

0     INCEPTION
1        DANGAL
2      3 IDIOTS
3     INCEPTION
4            PK
5       PATHAAN
6        DANGAL
7      THRILLER
8        ACTION
9        COMEDY
10       ACTION
11        DRAMA
Name: title, dtype: str

In [72]:
clean_titles.apply(lambda x: len(x))

0     9
1     6
2     8
3     9
4     2
5     7
6     6
7     8
8     6
9     6
10    6
11    5
Name: title, dtype: int64

In [142]:
movies["rating"]=movies["rating"].clip(0,10)
movies

        title     genre  rating  year  collection
0   Inception    Sci-Fi     8.8  2010         850
1      Dangal     Drama     8.4  2016        2000
2    3 Idiots    Comedy     8.4  2009         460
3   Inception    Sci-Fi     8.8  2010         850
4          Pk    comedy     8.1  2014         800
5     Pathaan    Action     5.8  2023        1050
6      Dangal     Drama     8.4  2016        2000
7    Thriller  Thriller     8.2  2015         110
8      Action    Action     7.8  2022        1200
9      comedy    comedy     8.1  2014         800
10     Action    Action     7.0  2023        1150
11      Drama     Drama     6.5  2020         150

In [143]:
movies["collection"]=movies["collection"].clip(0,2000)
movies

        title     genre  rating  year  collection
0   Inception    Sci-Fi     8.8  2010         850
1      Dangal     Drama     8.4  2016        2000
2    3 Idiots    Comedy     8.4  2009         460
3   Inception    Sci-Fi     8.8  2010         850
4          Pk    comedy     8.1  2014         800
5     Pathaan    Action     5.8  2023        1050
6      Dangal     Drama     8.4  2016        2000
7    Thriller  Thriller     8.2  2015         110
8      Action    Action     7.8  2022        1200
9      comedy    comedy     8.1  2014         800
10     Action    Action     7.0  2023        1150
11      Drama     Drama     6.5  2020         150

In [75]:
movies[movies["rating"]>=8]

       title     genre  rating  year  collection
0  Inception    Sci-Fi     8.8  2010         850
1     Dangal     Drama     8.4  2016        2000
2   3 Idiots    Comedy     8.4  2009         460
3  Inception    Sci-Fi     8.8  2010         850
4         Pk    comedy     8.1  2014         800
6     Dangal     Drama     8.4  2016        2000
7   Thriller  Thriller     8.2  2015         110
9     comedy    comedy     8.1  2014         800

In [76]:
movies[movies["genre"].isin(["Action","Drama"])]

      title   genre  rating  year  collection
1    Dangal   Drama     8.4  2016        2000
5   Pathaan  Action     5.8  2023        1050
6    Dangal   Drama     8.4  2016        2000
8    Action  Action     7.8  2022        1200
10   Action  Action     7.0  2023        1150
11    Drama   Drama     6.5  2020         150

In [77]:
movies[movies["year"].between(2015,2023)]

       title     genre  rating  year  collection
1     Dangal     Drama     8.4  2016        2000
5    Pathaan    Action     5.8  2023        1050
6     Dangal     Drama     8.4  2016        2000
7   Thriller  Thriller     8.2  2015         110
8     Action    Action     7.8  2022        1200
10    Action    Action     7.0  2023        1150
11     Drama     Drama     6.5  2020         150

In [78]:
movies.drop_duplicates()

        title     genre  rating  year  collection
0   Inception    Sci-Fi     8.8  2010         850
1      Dangal     Drama     8.4  2016        2000
2    3 Idiots    Comedy     8.4  2009         460
4          Pk    comedy     8.1  2014         800
5     Pathaan    Action     5.8  2023        1050
7    Thriller  Thriller     8.2  2015         110
8      Action    Action     7.8  2022        1200
9      comedy    comedy     8.1  2014         800
10     Action    Action     7.0  2023        1150
11      Drama     Drama     6.5  2020         150

In [79]:
movies.sort_values("rating",ascending=False).head()

       title   genre  rating  year  collection
0  Inception  Sci-Fi     8.8  2010         850
3  Inception  Sci-Fi     8.8  2010         850
1     Dangal   Drama     8.4  2016        2000
2   3 Idiots  Comedy     8.4  2009         460
6     Dangal   Drama     8.4  2016        2000

In [80]:
movies.sort_values("collection",ascending=False).head()

      title   genre  rating  year  collection
1    Dangal   Drama     8.4  2016        2000
6    Dangal   Drama     8.4  2016        2000
8    Action  Action     7.8  2022        1200
10   Action  Action     7.0  2023        1150
5   Pathaan  Action     5.8  2023        1050

In [81]:
movies["genre"].value_counts()

genre
Drama       3
Action      3
Sci-Fi      2
comedy      2
Comedy      1
Thriller    1
Name: count, dtype: int64

In [82]:
movies.groupby("genre")["rating"].mean().sort_values(ascending=False)

genre
Sci-Fi      8.800000
Comedy      8.400000
Thriller    8.200000
comedy      8.100000
Drama       7.766667
Action      6.866667
Name: rating, dtype: float64

In [83]:
movies.groupby("genre")["collection"].mean().sort_values(ascending=False)

genre
Drama       1383.333333
Action      1133.333333
Sci-Fi       850.000000
comedy       800.000000
Comedy       460.000000
Thriller     110.000000
Name: collection, dtype: float64

In [84]:
movies

        title     genre  rating  year  collection
0   Inception    Sci-Fi     8.8  2010         850
1      Dangal     Drama     8.4  2016        2000
2    3 Idiots    Comedy     8.4  2009         460
3   Inception    Sci-Fi     8.8  2010         850
4          Pk    comedy     8.1  2014         800
5     Pathaan    Action     5.8  2023        1050
6      Dangal     Drama     8.4  2016        2000
7    Thriller  Thriller     8.2  2015         110
8      Action    Action     7.8  2022        1200
9      comedy    comedy     8.1  2014         800
10     Action    Action     7.0  2023        1150
11      Drama     Drama     6.5  2020         150

# Program 3-Cricket Performance Analysis

In [85]:
import pandas as pd

In [86]:
import numpy as np

In [87]:
import sys

In [88]:
cricket=pd.DataFrame({
    "player":[
        "Virat","Rohit","Rahul","Hardik","Jadeja","Virat","Rohit","Gill","Pant","Bumrah","Rahul","Gill"
        ],
        "runs":[82,99,45,35,28,82,12,76,49,8,np.nan,76],
        "wickets":[0,0,1,2,3,0,0,0,1,4,1,0],
        "strike_rate":[112.4,118.2,91.5,135.0,102.2,112.4,72.0,108.6,101.5,80.0,95.0,108.6],
        "format":["ODI","ODI","ODI","T20","T20","ODI","T20","ODI","T20","T20","ODI","ODI"]
        })

In [89]:
cricket.shape

(12, 5)

In [90]:
cricket.dtypes

player             str
runs           float64
wickets          int64
strike_rate    float64
format             str
dtype: object

In [91]:
cricket.columns

Index(['player', 'runs', 'wickets', 'strike_rate', 'format'], dtype='str')

In [92]:
cricket.index

RangeIndex(start=0, stop=12, step=1)

In [93]:
cricket.values

array([['Virat', 82.0, 0, 112.4, 'ODI'],
       ['Rohit', 99.0, 0, 118.2, 'ODI'],
       ['Rahul', 45.0, 1, 91.5, 'ODI'],
       ['Hardik', 35.0, 2, 135.0, 'T20'],
       ['Jadeja', 28.0, 3, 102.2, 'T20'],
       ['Virat', 82.0, 0, 112.4, 'ODI'],
       ['Rohit', 12.0, 0, 72.0, 'T20'],
       ['Gill', 76.0, 0, 108.6, 'ODI'],
       ['Pant', 49.0, 1, 101.5, 'T20'],
       ['Bumrah', 8.0, 4, 80.0, 'T20'],
       ['Rahul', nan, 1, 95.0, 'ODI'],
       ['Gill', 76.0, 0, 108.6, 'ODI']], dtype=object)

In [94]:
cricket.head()

   player  runs  wickets  strike_rate format
0   Virat  82.0        0        112.4    ODI
1   Rohit  99.0        0        118.2    ODI
2   Rahul  45.0        1         91.5    ODI
3  Hardik  35.0        2        135.0    T20
4  Jadeja  28.0        3        102.2    T20

In [95]:
cricket.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   player       12 non-null     str
 1   runs         11 non-null     float64
 2   wickets      12 non-null     int64
 3   strike_rate  12 non-null     float64
 4   format       12 non-null     str
dtypes: float64(2), int64(1), str(2)
memory usage: 612.0 bytes

In [96]:
runs=cricket["runs"]

In [97]:
runs=runs.dropna()

In [98]:
runs.astype("int64")

0     82
1     99
2     45
3     35
4     28
5     82
6     12
7     76
8     49
9      8
11    76
Name: runs, dtype: int64

In [99]:
sys.getsizeof(runs)

208

In [100]:
runs[runs>=50]

0     82.0
1     99.0
5     82.0
7     76.0
11    76.0
Name: runs, dtype: float64

In [101]:
runs[runs.between(50,100)]

0     82.0
1     99.0
5     82.0
7     76.0
11    76.0
Name: runs, dtype: float64

In [102]:
runs[runs.isin([76,82,99])]

0     82.0
1     99.0
5     82.0
7     76.0
11    76.0
Name: runs, dtype: float64

In [103]:
runs.value_counts()

runs
82.0    2
76.0    2
99.0    1
45.0    1
35.0    1
28.0    1
12.0    1
49.0    1
8.0     1
Name: count, dtype: int64

In [104]:
runs.value_counts().sort_values(ascending=False)

runs
82.0    2
76.0    2
99.0    1
45.0    1
35.0    1
28.0    1
12.0    1
49.0    1
8.0     1
Name: count, dtype: int64

In [105]:
runs.mean()

np.float64(53.81818181818182)

In [144]:
wickets=cricket["wickets"]
wickets

0     0
1     0
2     1
3     2
4     3
5     0
6     0
7     0
8     1
9     4
10    1
11    0
Name: wickets, dtype: int64

In [107]:
wickets[wickets>0]

2     1
3     2
4     3
8     1
9     4
10    1
Name: wickets, dtype: int64

In [108]:
wickets[wickets.isin([1,2,3,])]

2     1
3     2
4     3
8     1
10    1
Name: wickets, dtype: int64

In [109]:
wickets.between(0,3)

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9     False
10     True
11     True
Name: wickets, dtype: bool

In [110]:
wickets.clip(0,4)

0     0
1     0
2     1
3     2
4     3
5     0
6     0
7     0
8     1
9     4
10    1
11    0
Name: wickets, dtype: int64

In [145]:
players=cricket["player"]
players

0      Virat
1      Rohit
2      Rahul
3     Hardik
4     Jadeja
5      Virat
6      Rohit
7       Gill
8       Pant
9     Bumrah
10     Rahul
11      Gill
Name: player, dtype: str

In [112]:
players.duplicated()

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7     False
8     False
9     False
10     True
11     True
Name: player, dtype: bool

In [113]:
players.duplicated().sum()

np.int64(4)

In [114]:
players.drop_duplicates()

0     Virat
1     Rohit
2     Rahul
3    Hardik
4    Jadeja
7      Gill
8      Pant
9    Bumrah
Name: player, dtype: str

In [115]:
players.value_counts()

player
Virat     2
Rohit     2
Rahul     2
Gill      2
Hardik    1
Jadeja    1
Pant      1
Bumrah    1
Name: count, dtype: int64

In [146]:
player_copy=players.copy()
player_copy

0      Virat
1      Rohit
2      Rahul
3     Hardik
4     Jadeja
5      Virat
6      Rohit
7       Gill
8       Pant
9     Bumrah
10     Rahul
11      Gill
Name: player, dtype: str

In [117]:
player_copy.apply(lambda x: x.upper())

0      VIRAT
1      ROHIT
2      RAHUL
3     HARDIK
4     JADEJA
5      VIRAT
6      ROHIT
7       GILL
8       PANT
9     BUMRAH
10     RAHUL
11      GILL
Name: player, dtype: str

In [118]:
player_copy.apply(lambda x: len(x))

0     5
1     5
2     5
3     6
4     6
5     5
6     5
7     4
8     4
9     6
10    5
11    4
Name: player, dtype: int64

In [147]:
cricket["runs_clean"]=cricket["runs"].fillna(0).astype("int64")
cricket

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
0,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
1,Rohit,99.0,0,118.2,ODI,99,Excellent,99,High
2,Rahul,45.0,1,91.5,ODI,45,Average,45,Medium
3,Hardik,35.0,2,135.0,T20,35,Average,35,High
4,Jadeja,28.0,3,102.2,T20,28,Average,28,Medium
5,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
6,Rohit,12.0,0,72.0,T20,12,Low,12,Low
7,Gill,76.0,0,108.6,ODI,76,Good,76,Medium
8,Pant,49.0,1,101.5,T20,49,Average,49,Medium
9,Bumrah,8.0,4,80.0,T20,8,Low,8,Low
10,Rahul,NaN,1,95.0,ODI,0,Low,0,Medium
11,Gill,76.0,0,108.6,ODI,76,Good,76,Medium

In [148]:
cricket["performance"]=cricket["runs_clean"].apply(lambda x: "Excellent" if x >=80 else ("Good" if x >=50 else("Average" if x >=25 else"Low")))
cricket

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
0,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
1,Rohit,99.0,0,118.2,ODI,99,Excellent,99,High
2,Rahul,45.0,1,91.5,ODI,45,Average,45,Medium
3,Hardik,35.0,2,135.0,T20,35,Average,35,High
4,Jadeja,28.0,3,102.2,T20,28,Average,28,Medium
5,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
6,Rohit,12.0,0,72.0,T20,12,Low,12,Low
7,Gill,76.0,0,108.6,ODI,76,Good,76,Medium
8,Pant,49.0,1,101.5,T20,49,Average,49,Medium
9,Bumrah,8.0,4,80.0,T20,8,Low,8,Low
10,Rahul,NaN,1,95.0,ODI,0,Low,0,Medium
11,Gill,76.0,0,108.6,ODI,76,Good,76,Medium

In [149]:
cricket["runs_limited"]=cricket["runs_clean"].clip(0,100)
cricket

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
0,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
1,Rohit,99.0,0,118.2,ODI,99,Excellent,99,High
2,Rahul,45.0,1,91.5,ODI,45,Average,45,Medium
3,Hardik,35.0,2,135.0,T20,35,Average,35,High
4,Jadeja,28.0,3,102.2,T20,28,Average,28,Medium
5,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
6,Rohit,12.0,0,72.0,T20,12,Low,12,Low
7,Gill,76.0,0,108.6,ODI,76,Good,76,Medium
8,Pant,49.0,1,101.5,T20,49,Average,49,Medium
9,Bumrah,8.0,4,80.0,T20,8,Low,8,Low
10,Rahul,NaN,1,95.0,ODI,0,Low,0,Medium
11,Gill,76.0,0,108.6,ODI,76,Good,76,Medium

In [150]:
cricket["sr_category"]=cricket["strike_rate"].apply(lambda x: "High" if x >=110 else("Medium" if x >=90 else "Low")) 
cricket

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
0,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
1,Rohit,99.0,0,118.2,ODI,99,Excellent,99,High
2,Rahul,45.0,1,91.5,ODI,45,Average,45,Medium
3,Hardik,35.0,2,135.0,T20,35,Average,35,High
4,Jadeja,28.0,3,102.2,T20,28,Average,28,Medium
5,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
6,Rohit,12.0,0,72.0,T20,12,Low,12,Low
7,Gill,76.0,0,108.6,ODI,76,Good,76,Medium
8,Pant,49.0,1,101.5,T20,49,Average,49,Medium
9,Bumrah,8.0,4,80.0,T20,8,Low,8,Low
10,Rahul,NaN,1,95.0,ODI,0,Low,0,Medium
11,Gill,76.0,0,108.6,ODI,76,Good,76,Medium

In [123]:
cricket[cricket["runs_clean"]>=50]

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
0,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
1,Rohit,99.0,0,118.2,ODI,99,Excellent,99,High
5,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
7,Gill,76.0,0,108.6,ODI,76,Good,76,Medium
11,Gill,76.0,0,108.6,ODI,76,Good,76,Medium

In [124]:
cricket[cricket["format"].isin(["ODI","T20"])]

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
0,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
1,Rohit,99.0,0,118.2,ODI,99,Excellent,99,High
2,Rahul,45.0,1,91.5,ODI,45,Average,45,Medium
3,Hardik,35.0,2,135.0,T20,35,Average,35,High
4,Jadeja,28.0,3,102.2,T20,28,Average,28,Medium
5,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
6,Rohit,12.0,0,72.0,T20,12,Low,12,Low
7,Gill,76.0,0,108.6,ODI,76,Good,76,Medium
8,Pant,49.0,1,101.5,T20,49,Average,49,Medium
9,Bumrah,8.0,4,80.0,T20,8,Low,8,Low
10,Rahul,NaN,1,95.0,ODI,0,Low,0,Medium
11,Gill,76.0,0,108.6,ODI,76,Good,76,Medium

In [125]:
cricket[cricket["strike_rate"].between(90,120)]

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
0,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
1,Rohit,99.0,0,118.2,ODI,99,Excellent,99,High
2,Rahul,45.0,1,91.5,ODI,45,Average,45,Medium
4,Jadeja,28.0,3,102.2,T20,28,Average,28,Medium
5,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
7,Gill,76.0,0,108.6,ODI,76,Good,76,Medium
8,Pant,49.0,1,101.5,T20,49,Average,49,Medium
10,Rahul,NaN,1,95.0,ODI,0,Low,0,Medium
11,Gill,76.0,0,108.6,ODI,76,Good,76,Medium

In [126]:
cricket[cricket["wickets"].isin([1,3,4])]

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
2,Rahul,45.0,1,91.5,ODI,45,Average,45,Medium
4,Jadeja,28.0,3,102.2,T20,28,Average,28,Medium
8,Pant,49.0,1,101.5,T20,49,Average,49,Medium
9,Bumrah,8.0,4,80.0,T20,8,Low,8,Low
10,Rahul,NaN,1,95.0,ODI,0,Low,0,Medium

In [127]:
cricket.drop_duplicates()

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
0,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
1,Rohit,99.0,0,118.2,ODI,99,Excellent,99,High
2,Rahul,45.0,1,91.5,ODI,45,Average,45,Medium
3,Hardik,35.0,2,135.0,T20,35,Average,35,High
4,Jadeja,28.0,3,102.2,T20,28,Average,28,Medium
6,Rohit,12.0,0,72.0,T20,12,Low,12,Low
7,Gill,76.0,0,108.6,ODI,76,Good,76,Medium
8,Pant,49.0,1,101.5,T20,49,Average,49,Medium
9,Bumrah,8.0,4,80.0,T20,8,Low,8,Low
10,Rahul,NaN,1,95.0,ODI,0,Low,0,Medium

In [128]:
cricket.sort_values("runs_clean",ascending=False).head()

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
1,Rohit,99.0,0,118.2,ODI,99,Excellent,99,High
0,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
5,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
7,Gill,76.0,0,108.6,ODI,76,Good,76,Medium
11,Gill,76.0,0,108.6,ODI,76,Good,76,Medium

In [129]:
cricket.sort_values("wickets",ascending=False).head()

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
9,Bumrah,8.0,4,80.0,T20,8,Low,8,Low
4,Jadeja,28.0,3,102.2,T20,28,Average,28,Medium
3,Hardik,35.0,2,135.0,T20,35,Average,35,High
2,Rahul,45.0,1,91.5,ODI,45,Average,45,Medium
8,Pant,49.0,1,101.5,T20,49,Average,49,Medium

In [130]:
cricket["format"].value_counts()

format
ODI    7
T20    5
Name: count, dtype: int64

In [131]:
cricket["performance"].value_counts()

performance
Average      4
Excellent    3
Low          3
Good         2
Name: count, dtype: int64

In [132]:
cricket.groupby("format")["runs_clean"].mean().sort_values(ascending=False)

format
ODI    65.714286
T20    26.400000
Name: runs_clean, dtype: float64

In [133]:
cricket.groupby("format")["wickets"].mean().sort_values(ascending=False)

format
T20    2.000000
ODI    0.285714
Name: wickets, dtype: float64

In [134]:
cricket

,player,runs,wickets,strike_rate,format,runs_clean,performance,runs_limited,sr_category
0,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
1,Rohit,99.0,0,118.2,ODI,99,Excellent,99,High
2,Rahul,45.0,1,91.5,ODI,45,Average,45,Medium
3,Hardik,35.0,2,135.0,T20,35,Average,35,High
4,Jadeja,28.0,3,102.2,T20,28,Average,28,Medium
5,Virat,82.0,0,112.4,ODI,82,Excellent,82,High
6,Rohit,12.0,0,72.0,T20,12,Low,12,Low
7,Gill,76.0,0,108.6,ODI,76,Good,76,Medium
8,Pant,49.0,1,101.5,T20,49,Average,49,Medium
9,Bumrah,8.0,4,80.0,T20,8,Low,8,Low
10,Rahul,NaN,1,95.0,ODI,0,Low,0,Medium
11,Gill,76.0,0,108.6,ODI,76,Good,76,Medium